// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverReq) Reset() {
	*x = CreateDriverReq{}
	mi := &file_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverReq) ProtoMessage() {}

func (x *CreateDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverReq.ProtoReflect.Descriptor instead.
func (*CreateDriverReq) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDriverReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverResp) Reset() {
	*x = CreateDriverResp{}
	mi := &file_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverResp) ProtoMessage() {}

func (x *CreateDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverResp.ProtoReflect.Descriptor instead.
func (*CreateDriverResp) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDriverResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverReq) Reset() {
	*x = GetDriverReq{}
	mi := &file_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverReq) ProtoMessage() {}

func (x *GetDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverReq.ProtoReflect.Descriptor instead.
func (*GetDriverReq) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{2}
}

func (x *GetDriverReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverResp) Reset() {
	*x = GetDriverResp{}
	mi := &file_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverResp) ProtoMessage() {}

func (x *GetDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverResp.ProtoReflect.Descriptor instead.
func (*GetDriverResp) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{3}
}

func (x *GetDriverResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDriverResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDriverResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriverReq) Reset() {
	*x = ListDriverReq{}
	mi := &file_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriverReq) ProtoMessage() {}

func (x *ListDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriverReq.ProtoReflect.Descriptor instead.
func (*ListDriverReq) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{4}
}

type DriverItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverItem) Reset() {
	*x = DriverItem{}
	mi := &file_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverItem) ProtoMessage() {}

func (x *DriverItem) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverItem.ProtoReflect.Descriptor instead.
func (*DriverItem) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{5}
}

func (x *DriverItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DriverItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriverResp) Reset() {
	*x = ListDriverResp{}
	mi := &file_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriverResp) ProtoMessage() {}

func (x *ListDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriverResp.ProtoReflect.Descriptor instead.
func (*ListDriverResp) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{6}
}

func (x *ListDriverResp) GetItems() []*DriverItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverReq) Reset() {
	*x = UpdateDriverReq{}
	mi := &file_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverReq) ProtoMessage() {}

func (x *UpdateDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverReq.ProtoReflect.Descriptor instead.
func (*UpdateDriverReq) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDriverReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDriverReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverResp) Reset() {
	*x = UpdateDriverResp{}
	mi := &file_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverResp) ProtoMessage() {}

func (x *UpdateDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverResp.ProtoReflect.Descriptor instead.
func (*UpdateDriverResp) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDriverResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDriverReq) Reset() {
	*x = DeleteDriverReq{}
	mi := &file_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDriverReq) ProtoMessage() {}

func (x *DeleteDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDriverReq.ProtoReflect.Descriptor instead.
func (*DeleteDriverReq) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDriverReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDriverResp) Reset() {
	*x = DeleteDriverResp{}
	mi := &file_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDriverResp) ProtoMessage() {}

func (x *DeleteDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDriverResp.ProtoReflect.Descriptor instead.
func (*DeleteDriverResp) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDriverResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetDriverProfile 新增：查询司机个人信息与接单统计
type GetDriverProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Days          int32                  `protobuf:"varint,3,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverProfileReq) Reset() {
	*x = GetDriverProfileReq{}
	mi := &file_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverProfileReq) ProtoMessage() {}

func (x *GetDriverProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverProfileReq.ProtoReflect.Descriptor instead.
func (*GetDriverProfileReq) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{11}
}

func (x *GetDriverProfileReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *GetDriverProfileReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetDriverProfileReq) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type GetDriverProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonalInfo  *PersonalInfo          `protobuf:"bytes,1,opt,name=personal_info,json=personalInfo,proto3" json:"personal_info,omitempty"`
	OrderStats    *OrderStats            `protobuf:"bytes,2,opt,name=order_stats,json=orderStats,proto3" json:"order_stats,omitempty"`
	VerifyStatus  int32                  `protobuf:"varint,3,opt,name=verify_status,json=verifyStatus,proto3" json:"verify_status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverProfileResp) Reset() {
	*x = GetDriverProfileResp{}
	mi := &file_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverProfileResp) ProtoMessage() {}

func (x *GetDriverProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverProfileResp.ProtoReflect.Descriptor instead.
func (*GetDriverProfileResp) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{12}
}

func (x *GetDriverProfileResp) GetPersonalInfo() *PersonalInfo {
	if x != nil {
		return x.PersonalInfo
	}
	return nil
}

func (x *GetDriverProfileResp) GetOrderStats() *OrderStats {
	if x != nil {
		return x.OrderStats
	}
	return nil
}

func (x *GetDriverProfileResp) GetVerifyStatus() int32 {
	if x != nil {
		return x.VerifyStatus
	}
	return 0
}

type PersonalInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ServiceScore  float64                `protobuf:"fixed64,3,opt,name=service_score,json=serviceScore,proto3" json:"service_score,omitempty"`
	OrderCount    int32                  `protobuf:"varint,4,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Plate         string                 `protobuf:"bytes,6,opt,name=plate,proto3" json:"plate,omitempty"`
	Car           string                 `protobuf:"bytes,7,opt,name=car,proto3" json:"car,omitempty"`
	Online        bool                   `protobuf:"varint,8,opt,name=online,proto3" json:"online,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalInfo) Reset() {
	*x = PersonalInfo{}
	mi := &file_driver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalInfo) ProtoMessage() {}

func (x *PersonalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalInfo.ProtoReflect.Descriptor instead.
func (*PersonalInfo) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{13}
}

func (x *PersonalInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PersonalInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PersonalInfo) GetServiceScore() float64 {
	if x != nil {
		return x.ServiceScore
	}
	return 0
}

func (x *PersonalInfo) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *PersonalInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PersonalInfo) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *PersonalInfo) GetCar() string {
	if x != nil {
		return x.Car
	}
	return ""
}

func (x *PersonalInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *PersonalInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderCount     int32                  `protobuf:"varint,1,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	Income         float64                `protobuf:"fixed64,2,opt,name=income,proto3" json:"income,omitempty"`
	OnlineDuration int32                  `protobuf:"varint,3,opt,name=online_duration,json=onlineDuration,proto3" json:"online_duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderStats) Reset() {
	*x = OrderStats{}
	mi := &file_driver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStats) ProtoMessage() {}

func (x *OrderStats) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStats.ProtoReflect.Descriptor instead.
func (*OrderStats) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{14}
}

func (x *OrderStats) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *OrderStats) GetIncome() float64 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *OrderStats) GetOnlineDuration() int32 {
	if x != nil {
		return x.OnlineDuration
	}
	return 0
}

var File_driver_proto protoreflect.FileDescriptor

const file_driver_proto_rawDesc = "" +
	"\n" +
	"\fdriver.proto\x12\x06driver\"%\n" +
	"\x0fCreateDriverReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\x10CreateDriverResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1e\n" +
	"\fGetDriverReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\rGetDriverResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\x0f\n" +
	"\rListDriverReq\"H\n" +
	"\n" +
	"DriverItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\":\n" +
	"\x0eListDriverResp\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.driver.DriverItemR\x05items\"5\n" +
	"\x0fUpdateDriverReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x10UpdateDriverResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\x0fDeleteDriverReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\",\n" +
	"\x10DeleteDriverResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Z\n" +
	"\x13GetDriverProfileReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x12\n" +
	"\x04days\x18\x03 \x01(\x05R\x04days\"\xab\x01\n" +
	"\x14GetDriverProfileResp\x129\n" +
	"\rpersonal_info\x18\x01 \x01(\v2\x14.driver.PersonalInfoR\fpersonalInfo\x123\n" +
	"\vorder_stats\x18\x02 \x01(\v2\x12.driver.OrderStatsR\n" +
	"orderStats\x12#\n" +
	"\rverify_status\x18\x03 \x01(\x05R\fverifyStatus\"\xf6\x01\n" +
	"\fPersonalInfo\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12#\n" +
	"\rservice_score\x18\x03 \x01(\x01R\fserviceScore\x12\x1f\n" +
	"\vorder_count\x18\x04 \x01(\x05R\n" +
	"orderCount\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05plate\x18\x06 \x01(\tR\x05plate\x12\x10\n" +
	"\x03car\x18\a \x01(\tR\x03car\x12\x16\n" +
	"\x06online\x18\b \x01(\bR\x06online\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"n\n" +
	"\n" +
	"OrderStats\x12\x1f\n" +
	"\vorder_count\x18\x01 \x01(\x05R\n" +
	"orderCount\x12\x16\n" +
	"\x06income\x18\x02 \x01(\x01R\x06income\x12'\n" +
	"\x0fonline_duration\x18\x03 \x01(\x05R\x0eonlineDuration2\xfa\x02\n" +
	"\rDriverService\x12;\n" +
	"\x06Create\x12\x17.driver.CreateDriverReq\x1a\x18.driver.CreateDriverResp\x122\n" +
	"\x03Get\x12\x14.driver.GetDriverReq\x1a\x15.driver.GetDriverResp\x125\n" +
	"\x04List\x12\x15.driver.ListDriverReq\x1a\x16.driver.ListDriverResp\x12;\n" +
	"\x06Update\x12\x17.driver.UpdateDriverReq\x1a\x18.driver.UpdateDriverResp\x12;\n" +
	"\x06Delete\x12\x17.driver.DeleteDriverReq\x1a\x18.driver.DeleteDriverResp\x12G\n" +
	"\n" +
	"GetProfile\x12\x1b.driver.GetDriverProfileReq\x1a\x1c.driver.GetDriverProfileRespB!Z\x1ftaketaxi/common/kitexGen/driverb\x06proto3"

var (
	file_driver_proto_rawDescOnce sync.Once
	file_driver_proto_rawDescData []byte
)

func file_driver_proto_rawDescGZIP() []byte {
	file_driver_proto_rawDescOnce.Do(func() {
		file_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_proto_rawDesc), len(file_driver_proto_rawDesc)))
	})
	return file_driver_proto_rawDescData
}

var file_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_driver_proto_goTypes = []any{
	(*CreateDriverReq)(nil),      // 0: driver.CreateDriverReq
	(*CreateDriverResp)(nil),     // 1: driver.CreateDriverResp
	(*GetDriverReq)(nil),         // 2: driver.GetDriverReq
	(*GetDriverResp)(nil),        // 3: driver.GetDriverResp
	(*ListDriverReq)(nil),        // 4: driver.ListDriverReq
	(*DriverItem)(nil),           // 5: driver.DriverItem
	(*ListDriverResp)(nil),       // 6: driver.ListDriverResp
	(*UpdateDriverReq)(nil),      // 7: driver.UpdateDriverReq
	(*UpdateDriverResp)(nil),     // 8: driver.UpdateDriverResp
	(*DeleteDriverReq)(nil),      // 9: driver.DeleteDriverReq
	(*DeleteDriverResp)(nil),     // 10: driver.DeleteDriverResp
	(*GetDriverProfileReq)(nil),  // 11: driver.GetDriverProfileReq
	(*GetDriverProfileResp)(nil), // 12: driver.GetDriverProfileResp
	(*PersonalInfo)(nil),         // 13: driver.PersonalInfo
	(*OrderStats)(nil),           // 14: driver.OrderStats
}
var file_driver_proto_depIdxs = []int32{
	5,  // 0: driver.ListDriverResp.items:type_name -> driver.DriverItem
	13, // 1: driver.GetDriverProfileResp.personal_info:type_name -> driver.PersonalInfo
	14, // 2: driver.GetDriverProfileResp.order_stats:type_name -> driver.OrderStats
	0,  // 3: driver.DriverService.Create:input_type -> driver.CreateDriverReq
	2,  // 4: driver.DriverService.Get:input_type -> driver.GetDriverReq
	4,  // 5: driver.DriverService.List:input_type -> driver.ListDriverReq
	7,  // 6: driver.DriverService.Update:input_type -> driver.UpdateDriverReq
	9,  // 7: driver.DriverService.Delete:input_type -> driver.DeleteDriverReq
	11, // 8: driver.DriverService.GetProfile:input_type -> driver.GetDriverProfileReq
	1,  // 9: driver.DriverService.Create:output_type -> driver.CreateDriverResp
	3,  // 10: driver.DriverService.Get:output_type -> driver.GetDriverResp
	6,  // 11: driver.DriverService.List:output_type -> driver.ListDriverResp
	8,  // 12: driver.DriverService.Update:output_type -> driver.UpdateDriverResp
	10, // 13: driver.DriverService.Delete:output_type -> driver.DeleteDriverResp
	12, // 14: driver.DriverService.GetProfile:output_type -> driver.GetDriverProfileResp
	9,  // [9:15] is the sub-list for method output_type
	3,  // [3:9] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_driver_proto_init() }
func file_driver_proto_init() {
	if File_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_proto_rawDesc), len(file_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_proto_goTypes,
		DependencyIndexes: file_driver_proto_depIdxs,
		MessageInfos:      file_driver_proto_msgTypes,
	}.Build()
	File_driver_proto = out.File
	file_driver_proto_goTypes = nil
	file_driver_proto_depIdxs = nil
}
