// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v3.19.1
// source: driver.proto

package kitexGen

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	DriverService_Create_FullMethodName             = "/driver.DriverService/Create"
	DriverService_Get_FullMethodName                = "/driver.DriverService/Get"
	DriverService_List_FullMethodName               = "/driver.DriverService/List"
	DriverService_Update_FullMethodName             = "/driver.DriverService/Update"
	DriverService_Delete_FullMethodName             = "/driver.DriverService/Delete"
	DriverService_GetProfile_FullMethodName         = "/driver.DriverService/GetProfile"
	DriverService_GetIncome_FullMethodName          = "/driver.DriverService/GetIncome"
	DriverService_ChangeMobile_FullMethodName       = "/driver.DriverService/ChangeMobile"
	DriverService_ChangePassword_FullMethodName     = "/driver.DriverService/ChangePassword"
	DriverService_ResetPassword_FullMethodName      = "/driver.DriverService/ResetPassword"
	DriverService_UpdateProfile_FullMethodName      = "/driver.DriverService/UpdateProfile"
	DriverService_UpdateRealname_FullMethodName     = "/driver.DriverService/UpdateRealname"
	DriverService_UpdateLicense_FullMethodName      = "/driver.DriverService/UpdateLicense"
	DriverService_UpdateVehicle_FullMethodName      = "/driver.DriverService/UpdateVehicle"
	DriverService_BindBankCard_FullMethodName       = "/driver.DriverService/BindBankCard"
	DriverService_GetBankCard_FullMethodName        = "/driver.DriverService/GetBankCard"
	DriverService_UpdateBankCard_FullMethodName     = "/driver.DriverService/UpdateBankCard"
	DriverService_GetWallet_FullMethodName          = "/driver.DriverService/GetWallet"
	DriverService_GetWithdrawPage_FullMethodName    = "/driver.DriverService/GetWithdrawPage"
	DriverService_ApplyWithdraw_FullMethodName      = "/driver.DriverService/ApplyWithdraw"
	DriverService_GetWithdrawRecords_FullMethodName = "/driver.DriverService/GetWithdrawRecords"
	DriverService_GetIncomeDetail_FullMethodName    = "/driver.DriverService/GetIncomeDetail"
)

// DriverServiceClient is the client API for DriverService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type DriverServiceClient interface {
	Create(ctx context.Context, in *CreateDriverReq, opts ...grpc.CallOption) (*CreateDriverResp, error)
	Get(ctx context.Context, in *GetDriverReq, opts ...grpc.CallOption) (*GetDriverResp, error)
	List(ctx context.Context, in *ListDriverReq, opts ...grpc.CallOption) (*ListDriverResp, error)
	Update(ctx context.Context, in *UpdateDriverReq, opts ...grpc.CallOption) (*UpdateDriverResp, error)
	Delete(ctx context.Context, in *DeleteDriverReq, opts ...grpc.CallOption) (*DeleteDriverResp, error)
	GetProfile(ctx context.Context, in *GetDriverProfileReq, opts ...grpc.CallOption) (*GetDriverProfileResp, error)
	GetIncome(ctx context.Context, in *GetDriverIncomeReq, opts ...grpc.CallOption) (*GetDriverIncomeResp, error)
	ChangeMobile(ctx context.Context, in *ChangeMobileReq, opts ...grpc.CallOption) (*ChangeMobileResp, error)
	ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*ChangePasswordResp, error)
	ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*ResetPasswordResp, error)
	UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*UpdateProfileResp, error)
	UpdateRealname(ctx context.Context, in *UpdateRealnameReq, opts ...grpc.CallOption) (*UpdateRealnameResp, error)
	UpdateLicense(ctx context.Context, in *UpdateLicenseReq, opts ...grpc.CallOption) (*UpdateLicenseResp, error)
	UpdateVehicle(ctx context.Context, in *UpdateVehicleReq, opts ...grpc.CallOption) (*UpdateVehicleResp, error)
	// 银行卡
	BindBankCard(ctx context.Context, in *BindBankCardReq, opts ...grpc.CallOption) (*BindBankCardResp, error)
	GetBankCard(ctx context.Context, in *GetBankCardReq, opts ...grpc.CallOption) (*GetBankCardResp, error)
	UpdateBankCard(ctx context.Context, in *UpdateBankCardReq, opts ...grpc.CallOption) (*UpdateBankCardResp, error)
	// 钱包 & 提现
	GetWallet(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetWalletResp, error)
	GetWithdrawPage(ctx context.Context, in *GetWithdrawPageReq, opts ...grpc.CallOption) (*GetWithdrawPageResp, error)
	ApplyWithdraw(ctx context.Context, in *ApplyWithdrawReq, opts ...grpc.CallOption) (*ApplyWithdrawResp, error)
	GetWithdrawRecords(ctx context.Context, in *GetWithdrawRecordsReq, opts ...grpc.CallOption) (*GetWithdrawRecordsResp, error)
	GetIncomeDetail(ctx context.Context, in *GetIncomeDetailReq, opts ...grpc.CallOption) (*GetIncomeDetailResp, error)
}

type driverServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewDriverServiceClient(cc grpc.ClientConnInterface) DriverServiceClient {
	return &driverServiceClient{cc}
}

func (c *driverServiceClient) Create(ctx context.Context, in *CreateDriverReq, opts ...grpc.CallOption) (*CreateDriverResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDriverResp)
	err := c.cc.Invoke(ctx, DriverService_Create_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) Get(ctx context.Context, in *GetDriverReq, opts ...grpc.CallOption) (*GetDriverResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverResp)
	err := c.cc.Invoke(ctx, DriverService_Get_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) List(ctx context.Context, in *ListDriverReq, opts ...grpc.CallOption) (*ListDriverResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ListDriverResp)
	err := c.cc.Invoke(ctx, DriverService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) Update(ctx context.Context, in *UpdateDriverReq, opts ...grpc.CallOption) (*UpdateDriverResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateDriverResp)
	err := c.cc.Invoke(ctx, DriverService_Update_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) Delete(ctx context.Context, in *DeleteDriverReq, opts ...grpc.CallOption) (*DeleteDriverResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DeleteDriverResp)
	err := c.cc.Invoke(ctx, DriverService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetProfile(ctx context.Context, in *GetDriverProfileReq, opts ...grpc.CallOption) (*GetDriverProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverProfileResp)
	err := c.cc.Invoke(ctx, DriverService_GetProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetIncome(ctx context.Context, in *GetDriverIncomeReq, opts ...grpc.CallOption) (*GetDriverIncomeResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetDriverIncomeResp)
	err := c.cc.Invoke(ctx, DriverService_GetIncome_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ChangeMobile(ctx context.Context, in *ChangeMobileReq, opts ...grpc.CallOption) (*ChangeMobileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangeMobileResp)
	err := c.cc.Invoke(ctx, DriverService_ChangeMobile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ChangePassword(ctx context.Context, in *ChangePasswordReq, opts ...grpc.CallOption) (*ChangePasswordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ChangePasswordResp)
	err := c.cc.Invoke(ctx, DriverService_ChangePassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ResetPassword(ctx context.Context, in *ResetPasswordReq, opts ...grpc.CallOption) (*ResetPasswordResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ResetPasswordResp)
	err := c.cc.Invoke(ctx, DriverService_ResetPassword_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UpdateProfile(ctx context.Context, in *UpdateProfileReq, opts ...grpc.CallOption) (*UpdateProfileResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateProfileResp)
	err := c.cc.Invoke(ctx, DriverService_UpdateProfile_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UpdateRealname(ctx context.Context, in *UpdateRealnameReq, opts ...grpc.CallOption) (*UpdateRealnameResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateRealnameResp)
	err := c.cc.Invoke(ctx, DriverService_UpdateRealname_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UpdateLicense(ctx context.Context, in *UpdateLicenseReq, opts ...grpc.CallOption) (*UpdateLicenseResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateLicenseResp)
	err := c.cc.Invoke(ctx, DriverService_UpdateLicense_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UpdateVehicle(ctx context.Context, in *UpdateVehicleReq, opts ...grpc.CallOption) (*UpdateVehicleResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateVehicleResp)
	err := c.cc.Invoke(ctx, DriverService_UpdateVehicle_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) BindBankCard(ctx context.Context, in *BindBankCardReq, opts ...grpc.CallOption) (*BindBankCardResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BindBankCardResp)
	err := c.cc.Invoke(ctx, DriverService_BindBankCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetBankCard(ctx context.Context, in *GetBankCardReq, opts ...grpc.CallOption) (*GetBankCardResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetBankCardResp)
	err := c.cc.Invoke(ctx, DriverService_GetBankCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) UpdateBankCard(ctx context.Context, in *UpdateBankCardReq, opts ...grpc.CallOption) (*UpdateBankCardResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(UpdateBankCardResp)
	err := c.cc.Invoke(ctx, DriverService_UpdateBankCard_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetWallet(ctx context.Context, in *GetWalletReq, opts ...grpc.CallOption) (*GetWalletResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWalletResp)
	err := c.cc.Invoke(ctx, DriverService_GetWallet_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetWithdrawPage(ctx context.Context, in *GetWithdrawPageReq, opts ...grpc.CallOption) (*GetWithdrawPageResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawPageResp)
	err := c.cc.Invoke(ctx, DriverService_GetWithdrawPage_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) ApplyWithdraw(ctx context.Context, in *ApplyWithdrawReq, opts ...grpc.CallOption) (*ApplyWithdrawResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ApplyWithdrawResp)
	err := c.cc.Invoke(ctx, DriverService_ApplyWithdraw_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetWithdrawRecords(ctx context.Context, in *GetWithdrawRecordsReq, opts ...grpc.CallOption) (*GetWithdrawRecordsResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetWithdrawRecordsResp)
	err := c.cc.Invoke(ctx, DriverService_GetWithdrawRecords_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *driverServiceClient) GetIncomeDetail(ctx context.Context, in *GetIncomeDetailReq, opts ...grpc.CallOption) (*GetIncomeDetailResp, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetIncomeDetailResp)
	err := c.cc.Invoke(ctx, DriverService_GetIncomeDetail_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// DriverServiceServer is the server API for DriverService service.
// All implementations must embed UnimplementedDriverServiceServer
// for forward compatibility.
type DriverServiceServer interface {
	Create(context.Context, *CreateDriverReq) (*CreateDriverResp, error)
	Get(context.Context, *GetDriverReq) (*GetDriverResp, error)
	List(context.Context, *ListDriverReq) (*ListDriverResp, error)
	Update(context.Context, *UpdateDriverReq) (*UpdateDriverResp, error)
	Delete(context.Context, *DeleteDriverReq) (*DeleteDriverResp, error)
	GetProfile(context.Context, *GetDriverProfileReq) (*GetDriverProfileResp, error)
	GetIncome(context.Context, *GetDriverIncomeReq) (*GetDriverIncomeResp, error)
	ChangeMobile(context.Context, *ChangeMobileReq) (*ChangeMobileResp, error)
	ChangePassword(context.Context, *ChangePasswordReq) (*ChangePasswordResp, error)
	ResetPassword(context.Context, *ResetPasswordReq) (*ResetPasswordResp, error)
	UpdateProfile(context.Context, *UpdateProfileReq) (*UpdateProfileResp, error)
	UpdateRealname(context.Context, *UpdateRealnameReq) (*UpdateRealnameResp, error)
	UpdateLicense(context.Context, *UpdateLicenseReq) (*UpdateLicenseResp, error)
	UpdateVehicle(context.Context, *UpdateVehicleReq) (*UpdateVehicleResp, error)
	// 银行卡
	BindBankCard(context.Context, *BindBankCardReq) (*BindBankCardResp, error)
	GetBankCard(context.Context, *GetBankCardReq) (*GetBankCardResp, error)
	UpdateBankCard(context.Context, *UpdateBankCardReq) (*UpdateBankCardResp, error)
	// 钱包 & 提现
	GetWallet(context.Context, *GetWalletReq) (*GetWalletResp, error)
	GetWithdrawPage(context.Context, *GetWithdrawPageReq) (*GetWithdrawPageResp, error)
	ApplyWithdraw(context.Context, *ApplyWithdrawReq) (*ApplyWithdrawResp, error)
	GetWithdrawRecords(context.Context, *GetWithdrawRecordsReq) (*GetWithdrawRecordsResp, error)
	GetIncomeDetail(context.Context, *GetIncomeDetailReq) (*GetIncomeDetailResp, error)
	mustEmbedUnimplementedDriverServiceServer()
}

// UnimplementedDriverServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedDriverServiceServer struct{}

func (UnimplementedDriverServiceServer) Create(context.Context, *CreateDriverReq) (*CreateDriverResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Create not implemented")
}
func (UnimplementedDriverServiceServer) Get(context.Context, *GetDriverReq) (*GetDriverResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Get not implemented")
}
func (UnimplementedDriverServiceServer) List(context.Context, *ListDriverReq) (*ListDriverResp, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedDriverServiceServer) Update(context.Context, *UpdateDriverReq) (*UpdateDriverResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Update not implemented")
}
func (UnimplementedDriverServiceServer) Delete(context.Context, *DeleteDriverReq) (*DeleteDriverResp, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedDriverServiceServer) GetProfile(context.Context, *GetDriverProfileReq) (*GetDriverProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetProfile not implemented")
}
func (UnimplementedDriverServiceServer) GetIncome(context.Context, *GetDriverIncomeReq) (*GetDriverIncomeResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIncome not implemented")
}
func (UnimplementedDriverServiceServer) ChangeMobile(context.Context, *ChangeMobileReq) (*ChangeMobileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangeMobile not implemented")
}
func (UnimplementedDriverServiceServer) ChangePassword(context.Context, *ChangePasswordReq) (*ChangePasswordResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ChangePassword not implemented")
}
func (UnimplementedDriverServiceServer) ResetPassword(context.Context, *ResetPasswordReq) (*ResetPasswordResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ResetPassword not implemented")
}
func (UnimplementedDriverServiceServer) UpdateProfile(context.Context, *UpdateProfileReq) (*UpdateProfileResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateProfile not implemented")
}
func (UnimplementedDriverServiceServer) UpdateRealname(context.Context, *UpdateRealnameReq) (*UpdateRealnameResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateRealname not implemented")
}
func (UnimplementedDriverServiceServer) UpdateLicense(context.Context, *UpdateLicenseReq) (*UpdateLicenseResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateLicense not implemented")
}
func (UnimplementedDriverServiceServer) UpdateVehicle(context.Context, *UpdateVehicleReq) (*UpdateVehicleResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateVehicle not implemented")
}
func (UnimplementedDriverServiceServer) BindBankCard(context.Context, *BindBankCardReq) (*BindBankCardResp, error) {
	return nil, status.Error(codes.Unimplemented, "method BindBankCard not implemented")
}
func (UnimplementedDriverServiceServer) GetBankCard(context.Context, *GetBankCardReq) (*GetBankCardResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetBankCard not implemented")
}
func (UnimplementedDriverServiceServer) UpdateBankCard(context.Context, *UpdateBankCardReq) (*UpdateBankCardResp, error) {
	return nil, status.Error(codes.Unimplemented, "method UpdateBankCard not implemented")
}
func (UnimplementedDriverServiceServer) GetWallet(context.Context, *GetWalletReq) (*GetWalletResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWallet not implemented")
}
func (UnimplementedDriverServiceServer) GetWithdrawPage(context.Context, *GetWithdrawPageReq) (*GetWithdrawPageResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWithdrawPage not implemented")
}
func (UnimplementedDriverServiceServer) ApplyWithdraw(context.Context, *ApplyWithdrawReq) (*ApplyWithdrawResp, error) {
	return nil, status.Error(codes.Unimplemented, "method ApplyWithdraw not implemented")
}
func (UnimplementedDriverServiceServer) GetWithdrawRecords(context.Context, *GetWithdrawRecordsReq) (*GetWithdrawRecordsResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetWithdrawRecords not implemented")
}
func (UnimplementedDriverServiceServer) GetIncomeDetail(context.Context, *GetIncomeDetailReq) (*GetIncomeDetailResp, error) {
	return nil, status.Error(codes.Unimplemented, "method GetIncomeDetail not implemented")
}
func (UnimplementedDriverServiceServer) mustEmbedUnimplementedDriverServiceServer() {}
func (UnimplementedDriverServiceServer) testEmbeddedByValue()                       {}

// UnsafeDriverServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to DriverServiceServer will
// result in compilation errors.
type UnsafeDriverServiceServer interface {
	mustEmbedUnimplementedDriverServiceServer()
}

func RegisterDriverServiceServer(s grpc.ServiceRegistrar, srv DriverServiceServer) {
	// If the following call panics, it indicates UnimplementedDriverServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&DriverService_ServiceDesc, srv)
}

func _DriverService_Create_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDriverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).Create(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_Create_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).Create(ctx, req.(*CreateDriverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_Get_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).Get(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_Get_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).Get(ctx, req.(*GetDriverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ListDriverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).List(ctx, req.(*ListDriverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_Update_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateDriverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).Update(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_Update_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).Update(ctx, req.(*UpdateDriverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DeleteDriverReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).Delete(ctx, req.(*DeleteDriverReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetProfile(ctx, req.(*GetDriverProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetIncome_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetDriverIncomeReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetIncome(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetIncome_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetIncome(ctx, req.(*GetDriverIncomeReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ChangeMobile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangeMobileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ChangeMobile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ChangeMobile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ChangeMobile(ctx, req.(*ChangeMobileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ChangePassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ChangePasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ChangePassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ChangePassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ChangePassword(ctx, req.(*ChangePasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ResetPassword_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ResetPasswordReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ResetPassword(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ResetPassword_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ResetPassword(ctx, req.(*ResetPasswordReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UpdateProfile_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateProfileReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UpdateProfile(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UpdateProfile_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UpdateProfile(ctx, req.(*UpdateProfileReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UpdateRealname_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateRealnameReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UpdateRealname(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UpdateRealname_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UpdateRealname(ctx, req.(*UpdateRealnameReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UpdateLicense_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateLicenseReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UpdateLicense(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UpdateLicense_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UpdateLicense(ctx, req.(*UpdateLicenseReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UpdateVehicle_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateVehicleReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UpdateVehicle(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UpdateVehicle_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UpdateVehicle(ctx, req.(*UpdateVehicleReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_BindBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BindBankCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).BindBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_BindBankCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).BindBankCard(ctx, req.(*BindBankCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetBankCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetBankCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetBankCard(ctx, req.(*GetBankCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_UpdateBankCard_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(UpdateBankCardReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).UpdateBankCard(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_UpdateBankCard_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).UpdateBankCard(ctx, req.(*UpdateBankCardReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetWallet_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWalletReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetWallet(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetWallet_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetWallet(ctx, req.(*GetWalletReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetWithdrawPage_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawPageReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetWithdrawPage(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetWithdrawPage_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetWithdrawPage(ctx, req.(*GetWithdrawPageReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_ApplyWithdraw_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ApplyWithdrawReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).ApplyWithdraw(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_ApplyWithdraw_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).ApplyWithdraw(ctx, req.(*ApplyWithdrawReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetWithdrawRecords_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetWithdrawRecordsReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetWithdrawRecords(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetWithdrawRecords_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetWithdrawRecords(ctx, req.(*GetWithdrawRecordsReq))
	}
	return interceptor(ctx, in, info, handler)
}

func _DriverService_GetIncomeDetail_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetIncomeDetailReq)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(DriverServiceServer).GetIncomeDetail(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: DriverService_GetIncomeDetail_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(DriverServiceServer).GetIncomeDetail(ctx, req.(*GetIncomeDetailReq))
	}
	return interceptor(ctx, in, info, handler)
}

// DriverService_ServiceDesc is the grpc.ServiceDesc for DriverService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var DriverService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "driver.DriverService",
	HandlerType: (*DriverServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Create",
			Handler:    _DriverService_Create_Handler,
		},
		{
			MethodName: "Get",
			Handler:    _DriverService_Get_Handler,
		},
		{
			MethodName: "List",
			Handler:    _DriverService_List_Handler,
		},
		{
			MethodName: "Update",
			Handler:    _DriverService_Update_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _DriverService_Delete_Handler,
		},
		{
			MethodName: "GetProfile",
			Handler:    _DriverService_GetProfile_Handler,
		},
		{
			MethodName: "GetIncome",
			Handler:    _DriverService_GetIncome_Handler,
		},
		{
			MethodName: "ChangeMobile",
			Handler:    _DriverService_ChangeMobile_Handler,
		},
		{
			MethodName: "ChangePassword",
			Handler:    _DriverService_ChangePassword_Handler,
		},
		{
			MethodName: "ResetPassword",
			Handler:    _DriverService_ResetPassword_Handler,
		},
		{
			MethodName: "UpdateProfile",
			Handler:    _DriverService_UpdateProfile_Handler,
		},
		{
			MethodName: "UpdateRealname",
			Handler:    _DriverService_UpdateRealname_Handler,
		},
		{
			MethodName: "UpdateLicense",
			Handler:    _DriverService_UpdateLicense_Handler,
		},
		{
			MethodName: "UpdateVehicle",
			Handler:    _DriverService_UpdateVehicle_Handler,
		},
		{
			MethodName: "BindBankCard",
			Handler:    _DriverService_BindBankCard_Handler,
		},
		{
			MethodName: "GetBankCard",
			Handler:    _DriverService_GetBankCard_Handler,
		},
		{
			MethodName: "UpdateBankCard",
			Handler:    _DriverService_UpdateBankCard_Handler,
		},
		{
			MethodName: "GetWallet",
			Handler:    _DriverService_GetWallet_Handler,
		},
		{
			MethodName: "GetWithdrawPage",
			Handler:    _DriverService_GetWithdrawPage_Handler,
		},
		{
			MethodName: "ApplyWithdraw",
			Handler:    _DriverService_ApplyWithdraw_Handler,
		},
		{
			MethodName: "GetWithdrawRecords",
			Handler:    _DriverService_GetWithdrawRecords_Handler,
		},
		{
			MethodName: "GetIncomeDetail",
			Handler:    _DriverService_GetIncomeDetail_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "driver.proto",
}
