// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverReq) Reset() {
	*x = CreateDriverReq{}
	mi := &file_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverReq) ProtoMessage() {}

func (x *CreateDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverReq.ProtoReflect.Descriptor instead.
func (*CreateDriverReq) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDriverReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverResp) Reset() {
	*x = CreateDriverResp{}
	mi := &file_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverResp) ProtoMessage() {}

func (x *CreateDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverResp.ProtoReflect.Descriptor instead.
func (*CreateDriverResp) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDriverResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverReq) Reset() {
	*x = GetDriverReq{}
	mi := &file_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverReq) ProtoMessage() {}

func (x *GetDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverReq.ProtoReflect.Descriptor instead.
func (*GetDriverReq) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{2}
}

func (x *GetDriverReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverResp) Reset() {
	*x = GetDriverResp{}
	mi := &file_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverResp) ProtoMessage() {}

func (x *GetDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverResp.ProtoReflect.Descriptor instead.
func (*GetDriverResp) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{3}
}

func (x *GetDriverResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDriverResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDriverResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriverReq) Reset() {
	*x = ListDriverReq{}
	mi := &file_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriverReq) ProtoMessage() {}

func (x *ListDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriverReq.ProtoReflect.Descriptor instead.
func (*ListDriverReq) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{4}
}

type DriverItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverItem) Reset() {
	*x = DriverItem{}
	mi := &file_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverItem) ProtoMessage() {}

func (x *DriverItem) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverItem.ProtoReflect.Descriptor instead.
func (*DriverItem) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{5}
}

func (x *DriverItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DriverItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriverResp) Reset() {
	*x = ListDriverResp{}
	mi := &file_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriverResp) ProtoMessage() {}

func (x *ListDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriverResp.ProtoReflect.Descriptor instead.
func (*ListDriverResp) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{6}
}

func (x *ListDriverResp) GetItems() []*DriverItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverReq) Reset() {
	*x = UpdateDriverReq{}
	mi := &file_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverReq) ProtoMessage() {}

func (x *UpdateDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverReq.ProtoReflect.Descriptor instead.
func (*UpdateDriverReq) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDriverReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDriverReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverResp) Reset() {
	*x = UpdateDriverResp{}
	mi := &file_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverResp) ProtoMessage() {}

func (x *UpdateDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverResp.ProtoReflect.Descriptor instead.
func (*UpdateDriverResp) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDriverResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDriverReq) Reset() {
	*x = DeleteDriverReq{}
	mi := &file_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDriverReq) ProtoMessage() {}

func (x *DeleteDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDriverReq.ProtoReflect.Descriptor instead.
func (*DeleteDriverReq) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDriverReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDriverResp) Reset() {
	*x = DeleteDriverResp{}
	mi := &file_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDriverResp) ProtoMessage() {}

func (x *DeleteDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDriverResp.ProtoReflect.Descriptor instead.
func (*DeleteDriverResp) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDriverResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// ///订单列表详情状态////////////////////////
type DriverDetailsReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderId       int64                  `protobuf:"varint,1,opt,name=orderId,proto3" json:"orderId,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverDetailsReq) Reset() {
	*x = DriverDetailsReq{}
	mi := &file_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverDetailsReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDetailsReq) ProtoMessage() {}

func (x *DriverDetailsReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDetailsReq.ProtoReflect.Descriptor instead.
func (*DriverDetailsReq) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{11}
}

func (x *DriverDetailsReq) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

type DriverDetailsResp struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	OrderId          int64                  `protobuf:"varint,1,opt,name=OrderId,proto3" json:"OrderId,omitempty"`
	OrderNo          string                 `protobuf:"bytes,2,opt,name=OrderNo,proto3" json:"OrderNo,omitempty"`
	OrderType        int64                  `protobuf:"varint,3,opt,name=OrderType,proto3" json:"OrderType,omitempty"`
	ServiceType      int64                  `protobuf:"varint,4,opt,name=ServiceType,proto3" json:"ServiceType,omitempty"`
	Status           int64                  `protobuf:"varint,5,opt,name=Status,proto3" json:"Status,omitempty"`
	DriverId         int64                  `protobuf:"varint,6,opt,name=DriverId,proto3" json:"DriverId,omitempty"`
	PassengerId      int64                  `protobuf:"varint,7,opt,name=PassengerId,proto3" json:"PassengerId,omitempty"`
	PassengerMobile  string                 `protobuf:"bytes,8,opt,name=PassengerMobile,proto3" json:"PassengerMobile,omitempty"`
	PassengerName    string                 `protobuf:"bytes,9,opt,name=PassengerName,proto3" json:"PassengerName,omitempty"`
	OriginAddress    string                 `protobuf:"bytes,10,opt,name=OriginAddress,proto3" json:"OriginAddress,omitempty"`
	OriginLat        float32                `protobuf:"fixed32,11,opt,name=OriginLat,proto3" json:"OriginLat,omitempty"`
	OriginLng        float32                `protobuf:"fixed32,12,opt,name=OriginLng,proto3" json:"OriginLng,omitempty"`
	OriginPoi        string                 `protobuf:"bytes,13,opt,name=OriginPoi,proto3" json:"OriginPoi,omitempty"`
	DestAddress      string                 `protobuf:"bytes,14,opt,name=DestAddress,proto3" json:"DestAddress,omitempty"`
	DestLat          float32                `protobuf:"fixed32,15,opt,name=DestLat,proto3" json:"DestLat,omitempty"`
	DestLng          float32                `protobuf:"fixed32,16,opt,name=DestLng,proto3" json:"DestLng,omitempty"`
	DestPoi          string                 `protobuf:"bytes,17,opt,name=DestPoi,proto3" json:"DestPoi,omitempty"`
	EstimateDistance int64                  `protobuf:"varint,18,opt,name=EstimateDistance,proto3" json:"EstimateDistance,omitempty"`
	EstimateDuration int64                  `protobuf:"varint,19,opt,name=EstimateDuration,proto3" json:"EstimateDuration,omitempty"`
	EstimateFee      float32                `protobuf:"fixed32,20,opt,name=EstimateFee,proto3" json:"EstimateFee,omitempty"`
	ActualDistance   int64                  `protobuf:"varint,21,opt,name=ActualDistance,proto3" json:"ActualDistance,omitempty"`
	ActualDuration   int64                  `protobuf:"varint,22,opt,name=ActualDuration,proto3" json:"ActualDuration,omitempty"`
	ActualFee        float32                `protobuf:"fixed32,23,opt,name=ActualFee,proto3" json:"ActualFee,omitempty"`
	BaseFee          float32                `protobuf:"fixed32,24,opt,name=BaseFee,proto3" json:"BaseFee,omitempty"`
	DistanceFee      float32                `protobuf:"fixed32,25,opt,name=DistanceFee,proto3" json:"DistanceFee,omitempty"`
	DurationFee      float32                `protobuf:"fixed32,26,opt,name=DurationFee,proto3" json:"DurationFee,omitempty"`
	WaitFee          float32                `protobuf:"fixed32,27,opt,name=WaitFee,proto3" json:"WaitFee,omitempty"`
	CouponId         int64                  `protobuf:"varint,28,opt,name=CouponId,proto3" json:"CouponId,omitempty"`
	CouponAmount     float32                `protobuf:"fixed32,29,opt,name=CouponAmount,proto3" json:"CouponAmount,omitempty"`
	PayStatus        int64                  `protobuf:"varint,30,opt,name=PayStatus,proto3" json:"PayStatus,omitempty"`
	PayType          int64                  `protobuf:"varint,31,opt,name=PayType,proto3" json:"PayType,omitempty"`
	PayTime          string                 `protobuf:"bytes,32,opt,name=PayTime,proto3" json:"PayTime,omitempty"`
	CancelReason     string                 `protobuf:"bytes,33,opt,name=CancelReason,proto3" json:"CancelReason,omitempty"`
	CancelBy         int64                  `protobuf:"varint,34,opt,name=CancelBy,proto3" json:"CancelBy,omitempty"`
	CancelTime       string                 `protobuf:"bytes,35,opt,name=CancelTime,proto3" json:"CancelTime,omitempty"`
	CityId           int64                  `protobuf:"varint,36,opt,name=CityId,proto3" json:"CityId,omitempty"`
	List             []*TripTrajectory      `protobuf:"bytes,37,rep,name=list,proto3" json:"list,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DriverDetailsResp) Reset() {
	*x = DriverDetailsResp{}
	mi := &file_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverDetailsResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverDetailsResp) ProtoMessage() {}

func (x *DriverDetailsResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverDetailsResp.ProtoReflect.Descriptor instead.
func (*DriverDetailsResp) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{12}
}

func (x *DriverDetailsResp) GetOrderId() int64 {
	if x != nil {
		return x.OrderId
	}
	return 0
}

func (x *DriverDetailsResp) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *DriverDetailsResp) GetOrderType() int64 {
	if x != nil {
		return x.OrderType
	}
	return 0
}

func (x *DriverDetailsResp) GetServiceType() int64 {
	if x != nil {
		return x.ServiceType
	}
	return 0
}

func (x *DriverDetailsResp) GetStatus() int64 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *DriverDetailsResp) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DriverDetailsResp) GetPassengerId() int64 {
	if x != nil {
		return x.PassengerId
	}
	return 0
}

func (x *DriverDetailsResp) GetPassengerMobile() string {
	if x != nil {
		return x.PassengerMobile
	}
	return ""
}

func (x *DriverDetailsResp) GetPassengerName() string {
	if x != nil {
		return x.PassengerName
	}
	return ""
}

func (x *DriverDetailsResp) GetOriginAddress() string {
	if x != nil {
		return x.OriginAddress
	}
	return ""
}

func (x *DriverDetailsResp) GetOriginLat() float32 {
	if x != nil {
		return x.OriginLat
	}
	return 0
}

func (x *DriverDetailsResp) GetOriginLng() float32 {
	if x != nil {
		return x.OriginLng
	}
	return 0
}

func (x *DriverDetailsResp) GetOriginPoi() string {
	if x != nil {
		return x.OriginPoi
	}
	return ""
}

func (x *DriverDetailsResp) GetDestAddress() string {
	if x != nil {
		return x.DestAddress
	}
	return ""
}

func (x *DriverDetailsResp) GetDestLat() float32 {
	if x != nil {
		return x.DestLat
	}
	return 0
}

func (x *DriverDetailsResp) GetDestLng() float32 {
	if x != nil {
		return x.DestLng
	}
	return 0
}

func (x *DriverDetailsResp) GetDestPoi() string {
	if x != nil {
		return x.DestPoi
	}
	return ""
}

func (x *DriverDetailsResp) GetEstimateDistance() int64 {
	if x != nil {
		return x.EstimateDistance
	}
	return 0
}

func (x *DriverDetailsResp) GetEstimateDuration() int64 {
	if x != nil {
		return x.EstimateDuration
	}
	return 0
}

func (x *DriverDetailsResp) GetEstimateFee() float32 {
	if x != nil {
		return x.EstimateFee
	}
	return 0
}

func (x *DriverDetailsResp) GetActualDistance() int64 {
	if x != nil {
		return x.ActualDistance
	}
	return 0
}

func (x *DriverDetailsResp) GetActualDuration() int64 {
	if x != nil {
		return x.ActualDuration
	}
	return 0
}

func (x *DriverDetailsResp) GetActualFee() float32 {
	if x != nil {
		return x.ActualFee
	}
	return 0
}

func (x *DriverDetailsResp) GetBaseFee() float32 {
	if x != nil {
		return x.BaseFee
	}
	return 0
}

func (x *DriverDetailsResp) GetDistanceFee() float32 {
	if x != nil {
		return x.DistanceFee
	}
	return 0
}

func (x *DriverDetailsResp) GetDurationFee() float32 {
	if x != nil {
		return x.DurationFee
	}
	return 0
}

func (x *DriverDetailsResp) GetWaitFee() float32 {
	if x != nil {
		return x.WaitFee
	}
	return 0
}

func (x *DriverDetailsResp) GetCouponId() int64 {
	if x != nil {
		return x.CouponId
	}
	return 0
}

func (x *DriverDetailsResp) GetCouponAmount() float32 {
	if x != nil {
		return x.CouponAmount
	}
	return 0
}

func (x *DriverDetailsResp) GetPayStatus() int64 {
	if x != nil {
		return x.PayStatus
	}
	return 0
}

func (x *DriverDetailsResp) GetPayType() int64 {
	if x != nil {
		return x.PayType
	}
	return 0
}

func (x *DriverDetailsResp) GetPayTime() string {
	if x != nil {
		return x.PayTime
	}
	return ""
}

func (x *DriverDetailsResp) GetCancelReason() string {
	if x != nil {
		return x.CancelReason
	}
	return ""
}

func (x *DriverDetailsResp) GetCancelBy() int64 {
	if x != nil {
		return x.CancelBy
	}
	return 0
}

func (x *DriverDetailsResp) GetCancelTime() string {
	if x != nil {
		return x.CancelTime
	}
	return ""
}

func (x *DriverDetailsResp) GetCityId() int64 {
	if x != nil {
		return x.CityId
	}
	return 0
}

func (x *DriverDetailsResp) GetList() []*TripTrajectory {
	if x != nil {
		return x.List
	}
	return nil
}

type TripTrajectory struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             int64                  `protobuf:"varint,1,opt,name=Id,proto3" json:"Id,omitempty"`
	TripId         int64                  `protobuf:"varint,2,opt,name=TripId,proto3" json:"TripId,omitempty"`
	TrajectoryData string                 `protobuf:"bytes,3,opt,name=TrajectoryData,proto3" json:"TrajectoryData,omitempty"`
	PointCount     int64                  `protobuf:"varint,4,opt,name=PointCount,proto3" json:"PointCount,omitempty"`
	StartTime      string                 `protobuf:"bytes,5,opt,name=StartTime,proto3" json:"StartTime,omitempty"`
	EndTime        string                 `protobuf:"bytes,6,opt,name=EndTime,proto3" json:"EndTime,omitempty"`
	Distance       int64                  `protobuf:"varint,7,opt,name=Distance,proto3" json:"Distance,omitempty"`
	FileUrl        string                 `protobuf:"bytes,8,opt,name=FileUrl,proto3" json:"FileUrl,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *TripTrajectory) Reset() {
	*x = TripTrajectory{}
	mi := &file_driver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *TripTrajectory) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*TripTrajectory) ProtoMessage() {}

func (x *TripTrajectory) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use TripTrajectory.ProtoReflect.Descriptor instead.
func (*TripTrajectory) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{13}
}

func (x *TripTrajectory) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *TripTrajectory) GetTripId() int64 {
	if x != nil {
		return x.TripId
	}
	return 0
}

func (x *TripTrajectory) GetTrajectoryData() string {
	if x != nil {
		return x.TrajectoryData
	}
	return ""
}

func (x *TripTrajectory) GetPointCount() int64 {
	if x != nil {
		return x.PointCount
	}
	return 0
}

func (x *TripTrajectory) GetStartTime() string {
	if x != nil {
		return x.StartTime
	}
	return ""
}

func (x *TripTrajectory) GetEndTime() string {
	if x != nil {
		return x.EndTime
	}
	return ""
}

func (x *TripTrajectory) GetDistance() int64 {
	if x != nil {
		return x.Distance
	}
	return 0
}

func (x *TripTrajectory) GetFileUrl() string {
	if x != nil {
		return x.FileUrl
	}
	return ""
}

// ///司机订单列表////////////////////////
type DriverOrderListReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverOrderListReq) Reset() {
	*x = DriverOrderListReq{}
	mi := &file_driver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverOrderListReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverOrderListReq) ProtoMessage() {}

func (x *DriverOrderListReq) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverOrderListReq.ProtoReflect.Descriptor instead.
func (*DriverOrderListReq) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{14}
}

func (x *DriverOrderListReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *DriverOrderListReq) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DriverOrderListReq) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

type OrderListItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrderNo       string                 `protobuf:"bytes,1,opt,name=order_no,json=orderNo,proto3" json:"order_no,omitempty"`
	OriginPoi     string                 `protobuf:"bytes,2,opt,name=origin_poi,json=originPoi,proto3" json:"origin_poi,omitempty"`
	DestPoi       string                 `protobuf:"bytes,3,opt,name=dest_poi,json=destPoi,proto3" json:"dest_poi,omitempty"`
	StatusText    string                 `protobuf:"bytes,4,opt,name=status_text,json=statusText,proto3" json:"status_text,omitempty"`
	EstimateFee   int64                  `protobuf:"varint,5,opt,name=estimate_fee,json=estimateFee,proto3" json:"estimate_fee,omitempty"`
	CreatedAt     string                 `protobuf:"bytes,6,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *OrderListItem) Reset() {
	*x = OrderListItem{}
	mi := &file_driver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderListItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderListItem) ProtoMessage() {}

func (x *OrderListItem) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderListItem.ProtoReflect.Descriptor instead.
func (*OrderListItem) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{15}
}

func (x *OrderListItem) GetOrderNo() string {
	if x != nil {
		return x.OrderNo
	}
	return ""
}

func (x *OrderListItem) GetOriginPoi() string {
	if x != nil {
		return x.OriginPoi
	}
	return ""
}

func (x *OrderListItem) GetDestPoi() string {
	if x != nil {
		return x.DestPoi
	}
	return ""
}

func (x *OrderListItem) GetStatusText() string {
	if x != nil {
		return x.StatusText
	}
	return ""
}

func (x *OrderListItem) GetEstimateFee() int64 {
	if x != nil {
		return x.EstimateFee
	}
	return 0
}

func (x *OrderListItem) GetCreatedAt() string {
	if x != nil {
		return x.CreatedAt
	}
	return ""
}

type DriverOrderListResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Total         int32                  `protobuf:"varint,1,opt,name=total,proto3" json:"total,omitempty"`
	Page          int32                  `protobuf:"varint,2,opt,name=page,proto3" json:"page,omitempty"`
	PageSize      int32                  `protobuf:"varint,3,opt,name=page_size,json=pageSize,proto3" json:"page_size,omitempty"`
	Items         []*OrderListItem       `protobuf:"bytes,4,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverOrderListResp) Reset() {
	*x = DriverOrderListResp{}
	mi := &file_driver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverOrderListResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverOrderListResp) ProtoMessage() {}

func (x *DriverOrderListResp) ProtoReflect() protoreflect.Message {
	mi := &file_driver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverOrderListResp.ProtoReflect.Descriptor instead.
func (*DriverOrderListResp) Descriptor() ([]byte, []int) {
	return file_driver_proto_rawDescGZIP(), []int{16}
}

func (x *DriverOrderListResp) GetTotal() int32 {
	if x != nil {
		return x.Total
	}
	return 0
}

func (x *DriverOrderListResp) GetPage() int32 {
	if x != nil {
		return x.Page
	}
	return 0
}

func (x *DriverOrderListResp) GetPageSize() int32 {
	if x != nil {
		return x.PageSize
	}
	return 0
}

func (x *DriverOrderListResp) GetItems() []*OrderListItem {
	if x != nil {
		return x.Items
	}
	return nil
}

var File_driver_proto protoreflect.FileDescriptor

const file_driver_proto_rawDesc = "" +
	"\n" +
	"\fdriver.proto\x12\x06driver\"%\n" +
	"\x0fCreateDriverReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\x10CreateDriverResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1e\n" +
	"\fGetDriverReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\rGetDriverResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\x0f\n" +
	"\rListDriverReq\"H\n" +
	"\n" +
	"DriverItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\":\n" +
	"\x0eListDriverResp\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.driver.DriverItemR\x05items\"5\n" +
	"\x0fUpdateDriverReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x10UpdateDriverResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\x0fDeleteDriverReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\",\n" +
	"\x10DeleteDriverResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\",\n" +
	"\x10DriverDetailsReq\x12\x18\n" +
	"\aorderId\x18\x01 \x01(\x03R\aorderId\"\xb3\t\n" +
	"\x11DriverDetailsResp\x12\x18\n" +
	"\aOrderId\x18\x01 \x01(\x03R\aOrderId\x12\x18\n" +
	"\aOrderNo\x18\x02 \x01(\tR\aOrderNo\x12\x1c\n" +
	"\tOrderType\x18\x03 \x01(\x03R\tOrderType\x12 \n" +
	"\vServiceType\x18\x04 \x01(\x03R\vServiceType\x12\x16\n" +
	"\x06Status\x18\x05 \x01(\x03R\x06Status\x12\x1a\n" +
	"\bDriverId\x18\x06 \x01(\x03R\bDriverId\x12 \n" +
	"\vPassengerId\x18\a \x01(\x03R\vPassengerId\x12(\n" +
	"\x0fPassengerMobile\x18\b \x01(\tR\x0fPassengerMobile\x12$\n" +
	"\rPassengerName\x18\t \x01(\tR\rPassengerName\x12$\n" +
	"\rOriginAddress\x18\n" +
	" \x01(\tR\rOriginAddress\x12\x1c\n" +
	"\tOriginLat\x18\v \x01(\x02R\tOriginLat\x12\x1c\n" +
	"\tOriginLng\x18\f \x01(\x02R\tOriginLng\x12\x1c\n" +
	"\tOriginPoi\x18\r \x01(\tR\tOriginPoi\x12 \n" +
	"\vDestAddress\x18\x0e \x01(\tR\vDestAddress\x12\x18\n" +
	"\aDestLat\x18\x0f \x01(\x02R\aDestLat\x12\x18\n" +
	"\aDestLng\x18\x10 \x01(\x02R\aDestLng\x12\x18\n" +
	"\aDestPoi\x18\x11 \x01(\tR\aDestPoi\x12*\n" +
	"\x10EstimateDistance\x18\x12 \x01(\x03R\x10EstimateDistance\x12*\n" +
	"\x10EstimateDuration\x18\x13 \x01(\x03R\x10EstimateDuration\x12 \n" +
	"\vEstimateFee\x18\x14 \x01(\x02R\vEstimateFee\x12&\n" +
	"\x0eActualDistance\x18\x15 \x01(\x03R\x0eActualDistance\x12&\n" +
	"\x0eActualDuration\x18\x16 \x01(\x03R\x0eActualDuration\x12\x1c\n" +
	"\tActualFee\x18\x17 \x01(\x02R\tActualFee\x12\x18\n" +
	"\aBaseFee\x18\x18 \x01(\x02R\aBaseFee\x12 \n" +
	"\vDistanceFee\x18\x19 \x01(\x02R\vDistanceFee\x12 \n" +
	"\vDurationFee\x18\x1a \x01(\x02R\vDurationFee\x12\x18\n" +
	"\aWaitFee\x18\x1b \x01(\x02R\aWaitFee\x12\x1a\n" +
	"\bCouponId\x18\x1c \x01(\x03R\bCouponId\x12\"\n" +
	"\fCouponAmount\x18\x1d \x01(\x02R\fCouponAmount\x12\x1c\n" +
	"\tPayStatus\x18\x1e \x01(\x03R\tPayStatus\x12\x18\n" +
	"\aPayType\x18\x1f \x01(\x03R\aPayType\x12\x18\n" +
	"\aPayTime\x18  \x01(\tR\aPayTime\x12\"\n" +
	"\fCancelReason\x18! \x01(\tR\fCancelReason\x12\x1a\n" +
	"\bCancelBy\x18\" \x01(\x03R\bCancelBy\x12\x1e\n" +
	"\n" +
	"CancelTime\x18# \x01(\tR\n" +
	"CancelTime\x12\x16\n" +
	"\x06CityId\x18$ \x01(\x03R\x06CityId\x12*\n" +
	"\x04list\x18% \x03(\v2\x16.driver.TripTrajectoryR\x04list\"\xee\x01\n" +
	"\x0eTripTrajectory\x12\x0e\n" +
	"\x02Id\x18\x01 \x01(\x03R\x02Id\x12\x16\n" +
	"\x06TripId\x18\x02 \x01(\x03R\x06TripId\x12&\n" +
	"\x0eTrajectoryData\x18\x03 \x01(\tR\x0eTrajectoryData\x12\x1e\n" +
	"\n" +
	"PointCount\x18\x04 \x01(\x03R\n" +
	"PointCount\x12\x1c\n" +
	"\tStartTime\x18\x05 \x01(\tR\tStartTime\x12\x18\n" +
	"\aEndTime\x18\x06 \x01(\tR\aEndTime\x12\x1a\n" +
	"\bDistance\x18\a \x01(\x03R\bDistance\x12\x18\n" +
	"\aFileUrl\x18\b \x01(\tR\aFileUrl\"b\n" +
	"\x12DriverOrderListReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\"\xc7\x01\n" +
	"\rOrderListItem\x12\x19\n" +
	"\border_no\x18\x01 \x01(\tR\aorderNo\x12\x1d\n" +
	"\n" +
	"origin_poi\x18\x02 \x01(\tR\toriginPoi\x12\x19\n" +
	"\bdest_poi\x18\x03 \x01(\tR\adestPoi\x12\x1f\n" +
	"\vstatus_text\x18\x04 \x01(\tR\n" +
	"statusText\x12!\n" +
	"\festimate_fee\x18\x05 \x01(\x03R\vestimateFee\x12\x1d\n" +
	"\n" +
	"created_at\x18\x06 \x01(\tR\tcreatedAt\"\x89\x01\n" +
	"\x13DriverOrderListResp\x12\x14\n" +
	"\x05total\x18\x01 \x01(\x05R\x05total\x12\x12\n" +
	"\x04page\x18\x02 \x01(\x05R\x04page\x12\x1b\n" +
	"\tpage_size\x18\x03 \x01(\x05R\bpageSize\x12+\n" +
	"\x05items\x18\x04 \x03(\v2\x15.driver.OrderListItemR\x05items2\xc3\x03\n" +
	"\rDriverService\x12;\n" +
	"\x06Create\x12\x17.driver.CreateDriverReq\x1a\x18.driver.CreateDriverResp\x122\n" +
	"\x03Get\x12\x14.driver.GetDriverReq\x1a\x15.driver.GetDriverResp\x125\n" +
	"\x04List\x12\x15.driver.ListDriverReq\x1a\x16.driver.ListDriverResp\x12;\n" +
	"\x06Update\x12\x17.driver.UpdateDriverReq\x1a\x18.driver.UpdateDriverResp\x12;\n" +
	"\x06Delete\x12\x17.driver.DeleteDriverReq\x1a\x18.driver.DeleteDriverResp\x12D\n" +
	"\rDriverDetails\x12\x18.driver.DriverDetailsReq\x1a\x19.driver.DriverDetailsResp\x12J\n" +
	"\x0fDriverOrderList\x12\x1a.driver.DriverOrderListReq\x1a\x1b.driver.DriverOrderListRespB!Z\x1ftaketaxi/common/kitexGen/driverb\x06proto3"

var (
	file_driver_proto_rawDescOnce sync.Once
	file_driver_proto_rawDescData []byte
)

func file_driver_proto_rawDescGZIP() []byte {
	file_driver_proto_rawDescOnce.Do(func() {
		file_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_driver_proto_rawDesc), len(file_driver_proto_rawDesc)))
	})
	return file_driver_proto_rawDescData
}

var file_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 17)
var file_driver_proto_goTypes = []any{
	(*CreateDriverReq)(nil),     // 0: driver.CreateDriverReq
	(*CreateDriverResp)(nil),    // 1: driver.CreateDriverResp
	(*GetDriverReq)(nil),        // 2: driver.GetDriverReq
	(*GetDriverResp)(nil),       // 3: driver.GetDriverResp
	(*ListDriverReq)(nil),       // 4: driver.ListDriverReq
	(*DriverItem)(nil),          // 5: driver.DriverItem
	(*ListDriverResp)(nil),      // 6: driver.ListDriverResp
	(*UpdateDriverReq)(nil),     // 7: driver.UpdateDriverReq
	(*UpdateDriverResp)(nil),    // 8: driver.UpdateDriverResp
	(*DeleteDriverReq)(nil),     // 9: driver.DeleteDriverReq
	(*DeleteDriverResp)(nil),    // 10: driver.DeleteDriverResp
	(*DriverDetailsReq)(nil),    // 11: driver.DriverDetailsReq
	(*DriverDetailsResp)(nil),   // 12: driver.DriverDetailsResp
	(*TripTrajectory)(nil),      // 13: driver.TripTrajectory
	(*DriverOrderListReq)(nil),  // 14: driver.DriverOrderListReq
	(*OrderListItem)(nil),       // 15: driver.OrderListItem
	(*DriverOrderListResp)(nil), // 16: driver.DriverOrderListResp
}
var file_driver_proto_depIdxs = []int32{
	5,  // 0: driver.ListDriverResp.items:type_name -> driver.DriverItem
	13, // 1: driver.DriverDetailsResp.list:type_name -> driver.TripTrajectory
	15, // 2: driver.DriverOrderListResp.items:type_name -> driver.OrderListItem
	0,  // 3: driver.DriverService.Create:input_type -> driver.CreateDriverReq
	2,  // 4: driver.DriverService.Get:input_type -> driver.GetDriverReq
	4,  // 5: driver.DriverService.List:input_type -> driver.ListDriverReq
	7,  // 6: driver.DriverService.Update:input_type -> driver.UpdateDriverReq
	9,  // 7: driver.DriverService.Delete:input_type -> driver.DeleteDriverReq
	11, // 8: driver.DriverService.DriverDetails:input_type -> driver.DriverDetailsReq
	14, // 9: driver.DriverService.DriverOrderList:input_type -> driver.DriverOrderListReq
	1,  // 10: driver.DriverService.Create:output_type -> driver.CreateDriverResp
	3,  // 11: driver.DriverService.Get:output_type -> driver.GetDriverResp
	6,  // 12: driver.DriverService.List:output_type -> driver.ListDriverResp
	8,  // 13: driver.DriverService.Update:output_type -> driver.UpdateDriverResp
	10, // 14: driver.DriverService.Delete:output_type -> driver.DeleteDriverResp
	12, // 15: driver.DriverService.DriverDetails:output_type -> driver.DriverDetailsResp
	16, // 16: driver.DriverService.DriverOrderList:output_type -> driver.DriverOrderListResp
	10, // [10:17] is the sub-list for method output_type
	3,  // [3:10] is the sub-list for method input_type
	3,  // [3:3] is the sub-list for extension type_name
	3,  // [3:3] is the sub-list for extension extendee
	0,  // [0:3] is the sub-list for field type_name
}

func init() { file_driver_proto_init() }
func file_driver_proto_init() {
	if File_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_driver_proto_rawDesc), len(file_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   17,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_driver_proto_goTypes,
		DependencyIndexes: file_driver_proto_depIdxs,
		MessageInfos:      file_driver_proto_msgTypes,
	}.Build()
	File_driver_proto = out.File
	file_driver_proto_goTypes = nil
	file_driver_proto_depIdxs = nil
}
