// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v3.19.1
// source: idl/driver.proto

package driver

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverReq) Reset() {
	*x = CreateDriverReq{}
	mi := &file_idl_driver_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverReq) ProtoMessage() {}

func (x *CreateDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverReq.ProtoReflect.Descriptor instead.
func (*CreateDriverReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{0}
}

func (x *CreateDriverReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDriverResp) Reset() {
	*x = CreateDriverResp{}
	mi := &file_idl_driver_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDriverResp) ProtoMessage() {}

func (x *CreateDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDriverResp.ProtoReflect.Descriptor instead.
func (*CreateDriverResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{1}
}

func (x *CreateDriverResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverReq) Reset() {
	*x = GetDriverReq{}
	mi := &file_idl_driver_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverReq) ProtoMessage() {}

func (x *GetDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverReq.ProtoReflect.Descriptor instead.
func (*GetDriverReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{2}
}

func (x *GetDriverReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type GetDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverResp) Reset() {
	*x = GetDriverResp{}
	mi := &file_idl_driver_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverResp) ProtoMessage() {}

func (x *GetDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverResp.ProtoReflect.Descriptor instead.
func (*GetDriverResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{3}
}

func (x *GetDriverResp) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *GetDriverResp) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *GetDriverResp) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriverReq) Reset() {
	*x = ListDriverReq{}
	mi := &file_idl_driver_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriverReq) ProtoMessage() {}

func (x *ListDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriverReq.ProtoReflect.Descriptor instead.
func (*ListDriverReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{4}
}

type DriverItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Status        int32                  `protobuf:"varint,3,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DriverItem) Reset() {
	*x = DriverItem{}
	mi := &file_idl_driver_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DriverItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DriverItem) ProtoMessage() {}

func (x *DriverItem) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DriverItem.ProtoReflect.Descriptor instead.
func (*DriverItem) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{5}
}

func (x *DriverItem) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *DriverItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *DriverItem) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type ListDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DriverItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListDriverResp) Reset() {
	*x = ListDriverResp{}
	mi := &file_idl_driver_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListDriverResp) ProtoMessage() {}

func (x *ListDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListDriverResp.ProtoReflect.Descriptor instead.
func (*ListDriverResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{6}
}

func (x *ListDriverResp) GetItems() []*DriverItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type UpdateDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverReq) Reset() {
	*x = UpdateDriverReq{}
	mi := &file_idl_driver_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverReq) ProtoMessage() {}

func (x *UpdateDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverReq.ProtoReflect.Descriptor instead.
func (*UpdateDriverReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{7}
}

func (x *UpdateDriverReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

func (x *UpdateDriverReq) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type UpdateDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateDriverResp) Reset() {
	*x = UpdateDriverResp{}
	mi := &file_idl_driver_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateDriverResp) ProtoMessage() {}

func (x *UpdateDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateDriverResp.ProtoReflect.Descriptor instead.
func (*UpdateDriverResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{8}
}

func (x *UpdateDriverResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type DeleteDriverReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            int64                  `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDriverReq) Reset() {
	*x = DeleteDriverReq{}
	mi := &file_idl_driver_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDriverReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDriverReq) ProtoMessage() {}

func (x *DeleteDriverReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDriverReq.ProtoReflect.Descriptor instead.
func (*DeleteDriverReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{9}
}

func (x *DeleteDriverReq) GetId() int64 {
	if x != nil {
		return x.Id
	}
	return 0
}

type DeleteDriverResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteDriverResp) Reset() {
	*x = DeleteDriverResp{}
	mi := &file_idl_driver_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteDriverResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteDriverResp) ProtoMessage() {}

func (x *DeleteDriverResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteDriverResp.ProtoReflect.Descriptor instead.
func (*DeleteDriverResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{10}
}

func (x *DeleteDriverResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

// GetDriverProfile 新增：查询司机个人信息与接单统计
type GetDriverProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Date          string                 `protobuf:"bytes,2,opt,name=date,proto3" json:"date,omitempty"`
	Days          int32                  `protobuf:"varint,3,opt,name=days,proto3" json:"days,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverProfileReq) Reset() {
	*x = GetDriverProfileReq{}
	mi := &file_idl_driver_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverProfileReq) ProtoMessage() {}

func (x *GetDriverProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverProfileReq.ProtoReflect.Descriptor instead.
func (*GetDriverProfileReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{11}
}

func (x *GetDriverProfileReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *GetDriverProfileReq) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *GetDriverProfileReq) GetDays() int32 {
	if x != nil {
		return x.Days
	}
	return 0
}

type GetDriverProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	PersonalInfo  *PersonalInfo          `protobuf:"bytes,1,opt,name=personal_info,json=personalInfo,proto3" json:"personal_info,omitempty"`
	OrderStats    *OrderStats            `protobuf:"bytes,2,opt,name=order_stats,json=orderStats,proto3" json:"order_stats,omitempty"`
	VerifyStatus  int32                  `protobuf:"varint,3,opt,name=verify_status,json=verifyStatus,proto3" json:"verify_status,omitempty"`
	RealnameInfo  *RealnameInfo          `protobuf:"bytes,4,opt,name=realname_info,json=realnameInfo,proto3" json:"realname_info,omitempty"`
	LicenseInfo   *LicenseInfo           `protobuf:"bytes,5,opt,name=license_info,json=licenseInfo,proto3" json:"license_info,omitempty"`
	VehicleInfo   *VehicleInfo           `protobuf:"bytes,6,opt,name=vehicle_info,json=vehicleInfo,proto3" json:"vehicle_info,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverProfileResp) Reset() {
	*x = GetDriverProfileResp{}
	mi := &file_idl_driver_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverProfileResp) ProtoMessage() {}

func (x *GetDriverProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverProfileResp.ProtoReflect.Descriptor instead.
func (*GetDriverProfileResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{12}
}

func (x *GetDriverProfileResp) GetPersonalInfo() *PersonalInfo {
	if x != nil {
		return x.PersonalInfo
	}
	return nil
}

func (x *GetDriverProfileResp) GetOrderStats() *OrderStats {
	if x != nil {
		return x.OrderStats
	}
	return nil
}

func (x *GetDriverProfileResp) GetVerifyStatus() int32 {
	if x != nil {
		return x.VerifyStatus
	}
	return 0
}

func (x *GetDriverProfileResp) GetRealnameInfo() *RealnameInfo {
	if x != nil {
		return x.RealnameInfo
	}
	return nil
}

func (x *GetDriverProfileResp) GetLicenseInfo() *LicenseInfo {
	if x != nil {
		return x.LicenseInfo
	}
	return nil
}

func (x *GetDriverProfileResp) GetVehicleInfo() *VehicleInfo {
	if x != nil {
		return x.VehicleInfo
	}
	return nil
}

// 实名认证信息（用于前端回显已提交数据）
type RealnameInfo struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	RealName       string                 `protobuf:"bytes,1,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdCardFrontUrl string                 `protobuf:"bytes,2,opt,name=id_card_front_url,json=idCardFrontUrl,proto3" json:"id_card_front_url,omitempty"`
	IdCardBackUrl  string                 `protobuf:"bytes,3,opt,name=id_card_back_url,json=idCardBackUrl,proto3" json:"id_card_back_url,omitempty"`
	Status         int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *RealnameInfo) Reset() {
	*x = RealnameInfo{}
	mi := &file_idl_driver_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RealnameInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RealnameInfo) ProtoMessage() {}

func (x *RealnameInfo) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RealnameInfo.ProtoReflect.Descriptor instead.
func (*RealnameInfo) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{13}
}

func (x *RealnameInfo) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *RealnameInfo) GetIdCardFrontUrl() string {
	if x != nil {
		return x.IdCardFrontUrl
	}
	return ""
}

func (x *RealnameInfo) GetIdCardBackUrl() string {
	if x != nil {
		return x.IdCardBackUrl
	}
	return ""
}

func (x *RealnameInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 驾驶证认证信息（用于前端回显已提交数据）
type LicenseInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	LicenseNo     string                 `protobuf:"bytes,1,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	LicenseType   string                 `protobuf:"bytes,2,opt,name=license_type,json=licenseType,proto3" json:"license_type,omitempty"`
	LicenseUrl    string                 `protobuf:"bytes,3,opt,name=license_url,json=licenseUrl,proto3" json:"license_url,omitempty"`
	Status        int32                  `protobuf:"varint,4,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *LicenseInfo) Reset() {
	*x = LicenseInfo{}
	mi := &file_idl_driver_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *LicenseInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*LicenseInfo) ProtoMessage() {}

func (x *LicenseInfo) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use LicenseInfo.ProtoReflect.Descriptor instead.
func (*LicenseInfo) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{14}
}

func (x *LicenseInfo) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *LicenseInfo) GetLicenseType() string {
	if x != nil {
		return x.LicenseType
	}
	return ""
}

func (x *LicenseInfo) GetLicenseUrl() string {
	if x != nil {
		return x.LicenseUrl
	}
	return ""
}

func (x *LicenseInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

// 车辆信息（用于前端回显已提交数据）
type VehicleInfo struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	PlateNo           string                 `protobuf:"bytes,1,opt,name=plate_no,json=plateNo,proto3" json:"plate_no,omitempty"`
	VehicleBrand      string                 `protobuf:"bytes,2,opt,name=vehicle_brand,json=vehicleBrand,proto3" json:"vehicle_brand,omitempty"`
	VehicleModel      string                 `protobuf:"bytes,3,opt,name=vehicle_model,json=vehicleModel,proto3" json:"vehicle_model,omitempty"`
	VehicleColor      string                 `protobuf:"bytes,4,opt,name=vehicle_color,json=vehicleColor,proto3" json:"vehicle_color,omitempty"`
	SeatCount         int32                  `protobuf:"varint,5,opt,name=seat_count,json=seatCount,proto3" json:"seat_count,omitempty"`
	DrivingLicenseUrl string                 `protobuf:"bytes,6,opt,name=driving_license_url,json=drivingLicenseUrl,proto3" json:"driving_license_url,omitempty"`
	VehiclePhotoUrl   string                 `protobuf:"bytes,7,opt,name=vehicle_photo_url,json=vehiclePhotoUrl,proto3" json:"vehicle_photo_url,omitempty"`
	Status            int32                  `protobuf:"varint,8,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VehicleInfo) Reset() {
	*x = VehicleInfo{}
	mi := &file_idl_driver_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VehicleInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VehicleInfo) ProtoMessage() {}

func (x *VehicleInfo) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VehicleInfo.ProtoReflect.Descriptor instead.
func (*VehicleInfo) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{15}
}

func (x *VehicleInfo) GetPlateNo() string {
	if x != nil {
		return x.PlateNo
	}
	return ""
}

func (x *VehicleInfo) GetVehicleBrand() string {
	if x != nil {
		return x.VehicleBrand
	}
	return ""
}

func (x *VehicleInfo) GetVehicleModel() string {
	if x != nil {
		return x.VehicleModel
	}
	return ""
}

func (x *VehicleInfo) GetVehicleColor() string {
	if x != nil {
		return x.VehicleColor
	}
	return ""
}

func (x *VehicleInfo) GetSeatCount() int32 {
	if x != nil {
		return x.SeatCount
	}
	return 0
}

func (x *VehicleInfo) GetDrivingLicenseUrl() string {
	if x != nil {
		return x.DrivingLicenseUrl
	}
	return ""
}

func (x *VehicleInfo) GetVehiclePhotoUrl() string {
	if x != nil {
		return x.VehiclePhotoUrl
	}
	return ""
}

func (x *VehicleInfo) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

type PersonalInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nickname      string                 `protobuf:"bytes,1,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,2,opt,name=avatar,proto3" json:"avatar,omitempty"`
	ServiceScore  float64                `protobuf:"fixed64,3,opt,name=service_score,json=serviceScore,proto3" json:"service_score,omitempty"`
	OrderCount    int32                  `protobuf:"varint,4,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	Phone         string                 `protobuf:"bytes,5,opt,name=phone,proto3" json:"phone,omitempty"`
	Plate         string                 `protobuf:"bytes,6,opt,name=plate,proto3" json:"plate,omitempty"`
	Car           string                 `protobuf:"bytes,7,opt,name=car,proto3" json:"car,omitempty"`
	Online        bool                   `protobuf:"varint,8,opt,name=online,proto3" json:"online,omitempty"`
	Status        string                 `protobuf:"bytes,9,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *PersonalInfo) Reset() {
	*x = PersonalInfo{}
	mi := &file_idl_driver_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *PersonalInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*PersonalInfo) ProtoMessage() {}

func (x *PersonalInfo) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use PersonalInfo.ProtoReflect.Descriptor instead.
func (*PersonalInfo) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{16}
}

func (x *PersonalInfo) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *PersonalInfo) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *PersonalInfo) GetServiceScore() float64 {
	if x != nil {
		return x.ServiceScore
	}
	return 0
}

func (x *PersonalInfo) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *PersonalInfo) GetPhone() string {
	if x != nil {
		return x.Phone
	}
	return ""
}

func (x *PersonalInfo) GetPlate() string {
	if x != nil {
		return x.Plate
	}
	return ""
}

func (x *PersonalInfo) GetCar() string {
	if x != nil {
		return x.Car
	}
	return ""
}

func (x *PersonalInfo) GetOnline() bool {
	if x != nil {
		return x.Online
	}
	return false
}

func (x *PersonalInfo) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

type OrderStats struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderCount     int32                  `protobuf:"varint,1,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	Income         float64                `protobuf:"fixed64,2,opt,name=income,proto3" json:"income,omitempty"`
	OnlineDuration int32                  `protobuf:"varint,3,opt,name=online_duration,json=onlineDuration,proto3" json:"online_duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *OrderStats) Reset() {
	*x = OrderStats{}
	mi := &file_idl_driver_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *OrderStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*OrderStats) ProtoMessage() {}

func (x *OrderStats) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use OrderStats.ProtoReflect.Descriptor instead.
func (*OrderStats) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{17}
}

func (x *OrderStats) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *OrderStats) GetIncome() float64 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *OrderStats) GetOnlineDuration() int32 {
	if x != nil {
		return x.OnlineDuration
	}
	return 0
}

// GetDriverIncome 收入明细查询
type GetDriverIncomeReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Period        string                 `protobuf:"bytes,2,opt,name=period,proto3" json:"period,omitempty"` // today/week/month
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverIncomeReq) Reset() {
	*x = GetDriverIncomeReq{}
	mi := &file_idl_driver_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverIncomeReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverIncomeReq) ProtoMessage() {}

func (x *GetDriverIncomeReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverIncomeReq.ProtoReflect.Descriptor instead.
func (*GetDriverIncomeReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{18}
}

func (x *GetDriverIncomeReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *GetDriverIncomeReq) GetPeriod() string {
	if x != nil {
		return x.Period
	}
	return ""
}

type DailyIncome struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Date          string                 `protobuf:"bytes,1,opt,name=date,proto3" json:"date,omitempty"`
	Income        float64                `protobuf:"fixed64,2,opt,name=income,proto3" json:"income,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DailyIncome) Reset() {
	*x = DailyIncome{}
	mi := &file_idl_driver_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DailyIncome) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DailyIncome) ProtoMessage() {}

func (x *DailyIncome) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DailyIncome.ProtoReflect.Descriptor instead.
func (*DailyIncome) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{19}
}

func (x *DailyIncome) GetDate() string {
	if x != nil {
		return x.Date
	}
	return ""
}

func (x *DailyIncome) GetIncome() float64 {
	if x != nil {
		return x.Income
	}
	return 0
}

type IncomeSummary struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	OrderCount     int32                  `protobuf:"varint,1,opt,name=order_count,json=orderCount,proto3" json:"order_count,omitempty"`
	Income         float64                `protobuf:"fixed64,2,opt,name=income,proto3" json:"income,omitempty"`
	OnlineDuration int32                  `protobuf:"varint,3,opt,name=online_duration,json=onlineDuration,proto3" json:"online_duration,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *IncomeSummary) Reset() {
	*x = IncomeSummary{}
	mi := &file_idl_driver_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IncomeSummary) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IncomeSummary) ProtoMessage() {}

func (x *IncomeSummary) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IncomeSummary.ProtoReflect.Descriptor instead.
func (*IncomeSummary) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{20}
}

func (x *IncomeSummary) GetOrderCount() int32 {
	if x != nil {
		return x.OrderCount
	}
	return 0
}

func (x *IncomeSummary) GetIncome() float64 {
	if x != nil {
		return x.Income
	}
	return 0
}

func (x *IncomeSummary) GetOnlineDuration() int32 {
	if x != nil {
		return x.OnlineDuration
	}
	return 0
}

type GetDriverIncomeResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Summary       *IncomeSummary         `protobuf:"bytes,1,opt,name=summary,proto3" json:"summary,omitempty"`
	Trend         []*DailyIncome         `protobuf:"bytes,2,rep,name=trend,proto3" json:"trend,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetDriverIncomeResp) Reset() {
	*x = GetDriverIncomeResp{}
	mi := &file_idl_driver_proto_msgTypes[21]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetDriverIncomeResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetDriverIncomeResp) ProtoMessage() {}

func (x *GetDriverIncomeResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[21]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetDriverIncomeResp.ProtoReflect.Descriptor instead.
func (*GetDriverIncomeResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{21}
}

func (x *GetDriverIncomeResp) GetSummary() *IncomeSummary {
	if x != nil {
		return x.Summary
	}
	return nil
}

func (x *GetDriverIncomeResp) GetTrend() []*DailyIncome {
	if x != nil {
		return x.Trend
	}
	return nil
}

// 修改手机号
type ChangeMobileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	NewMobile     string                 `protobuf:"bytes,2,opt,name=new_mobile,json=newMobile,proto3" json:"new_mobile,omitempty"`
	VerifyCode    string                 `protobuf:"bytes,3,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMobileReq) Reset() {
	*x = ChangeMobileReq{}
	mi := &file_idl_driver_proto_msgTypes[22]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMobileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMobileReq) ProtoMessage() {}

func (x *ChangeMobileReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[22]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMobileReq.ProtoReflect.Descriptor instead.
func (*ChangeMobileReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{22}
}

func (x *ChangeMobileReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *ChangeMobileReq) GetNewMobile() string {
	if x != nil {
		return x.NewMobile
	}
	return ""
}

func (x *ChangeMobileReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

type ChangeMobileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangeMobileResp) Reset() {
	*x = ChangeMobileResp{}
	mi := &file_idl_driver_proto_msgTypes[23]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangeMobileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangeMobileResp) ProtoMessage() {}

func (x *ChangeMobileResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[23]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangeMobileResp.ProtoReflect.Descriptor instead.
func (*ChangeMobileResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{23}
}

func (x *ChangeMobileResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChangeMobileResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 修改密码
type ChangePasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	OldPassword   string                 `protobuf:"bytes,2,opt,name=old_password,json=oldPassword,proto3" json:"old_password,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordReq) Reset() {
	*x = ChangePasswordReq{}
	mi := &file_idl_driver_proto_msgTypes[24]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordReq) ProtoMessage() {}

func (x *ChangePasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[24]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordReq.ProtoReflect.Descriptor instead.
func (*ChangePasswordReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{24}
}

func (x *ChangePasswordReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *ChangePasswordReq) GetOldPassword() string {
	if x != nil {
		return x.OldPassword
	}
	return ""
}

func (x *ChangePasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ChangePasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ChangePasswordResp) Reset() {
	*x = ChangePasswordResp{}
	mi := &file_idl_driver_proto_msgTypes[25]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ChangePasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ChangePasswordResp) ProtoMessage() {}

func (x *ChangePasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[25]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ChangePasswordResp.ProtoReflect.Descriptor instead.
func (*ChangePasswordResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{25}
}

func (x *ChangePasswordResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ChangePasswordResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// 重置密码（忘记密码）
type ResetPasswordReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Mobile        string                 `protobuf:"bytes,1,opt,name=mobile,proto3" json:"mobile,omitempty"`
	VerifyCode    string                 `protobuf:"bytes,2,opt,name=verify_code,json=verifyCode,proto3" json:"verify_code,omitempty"`
	NewPassword   string                 `protobuf:"bytes,3,opt,name=new_password,json=newPassword,proto3" json:"new_password,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordReq) Reset() {
	*x = ResetPasswordReq{}
	mi := &file_idl_driver_proto_msgTypes[26]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordReq) ProtoMessage() {}

func (x *ResetPasswordReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[26]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordReq.ProtoReflect.Descriptor instead.
func (*ResetPasswordReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{26}
}

func (x *ResetPasswordReq) GetMobile() string {
	if x != nil {
		return x.Mobile
	}
	return ""
}

func (x *ResetPasswordReq) GetVerifyCode() string {
	if x != nil {
		return x.VerifyCode
	}
	return ""
}

func (x *ResetPasswordReq) GetNewPassword() string {
	if x != nil {
		return x.NewPassword
	}
	return ""
}

type ResetPasswordResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ResetPasswordResp) Reset() {
	*x = ResetPasswordResp{}
	mi := &file_idl_driver_proto_msgTypes[27]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ResetPasswordResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ResetPasswordResp) ProtoMessage() {}

func (x *ResetPasswordResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[27]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ResetPasswordResp.ProtoReflect.Descriptor instead.
func (*ResetPasswordResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{27}
}

func (x *ResetPasswordResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *ResetPasswordResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateProfile 更新司机个人资料(通用，字段为空则不更新)
type UpdateProfileReq struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	DriverId      int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	Nickname      string                 `protobuf:"bytes,2,opt,name=nickname,proto3" json:"nickname,omitempty"`
	Avatar        string                 `protobuf:"bytes,3,opt,name=avatar,proto3" json:"avatar,omitempty"`
	Gender        int32                  `protobuf:"varint,4,opt,name=gender,proto3" json:"gender,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileReq) Reset() {
	*x = UpdateProfileReq{}
	mi := &file_idl_driver_proto_msgTypes[28]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileReq) ProtoMessage() {}

func (x *UpdateProfileReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[28]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileReq.ProtoReflect.Descriptor instead.
func (*UpdateProfileReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{28}
}

func (x *UpdateProfileReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *UpdateProfileReq) GetNickname() string {
	if x != nil {
		return x.Nickname
	}
	return ""
}

func (x *UpdateProfileReq) GetAvatar() string {
	if x != nil {
		return x.Avatar
	}
	return ""
}

func (x *UpdateProfileReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

type UpdateProfileResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateProfileResp) Reset() {
	*x = UpdateProfileResp{}
	mi := &file_idl_driver_proto_msgTypes[29]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateProfileResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateProfileResp) ProtoMessage() {}

func (x *UpdateProfileResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[29]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateProfileResp.ProtoReflect.Descriptor instead.
func (*UpdateProfileResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{29}
}

func (x *UpdateProfileResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateProfileResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateRealname 更新/提交实名认证
type UpdateRealnameReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DriverId       int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	RealName       string                 `protobuf:"bytes,2,opt,name=real_name,json=realName,proto3" json:"real_name,omitempty"`
	IdCardNo       string                 `protobuf:"bytes,3,opt,name=id_card_no,json=idCardNo,proto3" json:"id_card_no,omitempty"`
	IdCardFrontUrl string                 `protobuf:"bytes,4,opt,name=id_card_front_url,json=idCardFrontUrl,proto3" json:"id_card_front_url,omitempty"`
	IdCardBackUrl  string                 `protobuf:"bytes,5,opt,name=id_card_back_url,json=idCardBackUrl,proto3" json:"id_card_back_url,omitempty"`
	Gender         int32                  `protobuf:"varint,6,opt,name=gender,proto3" json:"gender,omitempty"`
	Birthday       string                 `protobuf:"bytes,7,opt,name=birthday,proto3" json:"birthday,omitempty"`
	Address        string                 `protobuf:"bytes,8,opt,name=address,proto3" json:"address,omitempty"`
	Nation         string                 `protobuf:"bytes,9,opt,name=nation,proto3" json:"nation,omitempty"`
	ExpireDate     string                 `protobuf:"bytes,10,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateRealnameReq) Reset() {
	*x = UpdateRealnameReq{}
	mi := &file_idl_driver_proto_msgTypes[30]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRealnameReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRealnameReq) ProtoMessage() {}

func (x *UpdateRealnameReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[30]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRealnameReq.ProtoReflect.Descriptor instead.
func (*UpdateRealnameReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{30}
}

func (x *UpdateRealnameReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *UpdateRealnameReq) GetRealName() string {
	if x != nil {
		return x.RealName
	}
	return ""
}

func (x *UpdateRealnameReq) GetIdCardNo() string {
	if x != nil {
		return x.IdCardNo
	}
	return ""
}

func (x *UpdateRealnameReq) GetIdCardFrontUrl() string {
	if x != nil {
		return x.IdCardFrontUrl
	}
	return ""
}

func (x *UpdateRealnameReq) GetIdCardBackUrl() string {
	if x != nil {
		return x.IdCardBackUrl
	}
	return ""
}

func (x *UpdateRealnameReq) GetGender() int32 {
	if x != nil {
		return x.Gender
	}
	return 0
}

func (x *UpdateRealnameReq) GetBirthday() string {
	if x != nil {
		return x.Birthday
	}
	return ""
}

func (x *UpdateRealnameReq) GetAddress() string {
	if x != nil {
		return x.Address
	}
	return ""
}

func (x *UpdateRealnameReq) GetNation() string {
	if x != nil {
		return x.Nation
	}
	return ""
}

func (x *UpdateRealnameReq) GetExpireDate() string {
	if x != nil {
		return x.ExpireDate
	}
	return ""
}

type UpdateRealnameResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateRealnameResp) Reset() {
	*x = UpdateRealnameResp{}
	mi := &file_idl_driver_proto_msgTypes[31]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateRealnameResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateRealnameResp) ProtoMessage() {}

func (x *UpdateRealnameResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[31]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateRealnameResp.ProtoReflect.Descriptor instead.
func (*UpdateRealnameResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{31}
}

func (x *UpdateRealnameResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateRealnameResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateLicense 更新/提交驾驶证认证
type UpdateLicenseReq struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	DriverId       int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	LicenseNo      string                 `protobuf:"bytes,2,opt,name=license_no,json=licenseNo,proto3" json:"license_no,omitempty"`
	LicenseType    string                 `protobuf:"bytes,3,opt,name=license_type,json=licenseType,proto3" json:"license_type,omitempty"`
	LicenseUrl     string                 `protobuf:"bytes,4,opt,name=license_url,json=licenseUrl,proto3" json:"license_url,omitempty"`
	FirstIssueDate string                 `protobuf:"bytes,5,opt,name=first_issue_date,json=firstIssueDate,proto3" json:"first_issue_date,omitempty"`
	IssueDate      string                 `protobuf:"bytes,6,opt,name=issue_date,json=issueDate,proto3" json:"issue_date,omitempty"`
	ExpireDate     string                 `protobuf:"bytes,7,opt,name=expire_date,json=expireDate,proto3" json:"expire_date,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *UpdateLicenseReq) Reset() {
	*x = UpdateLicenseReq{}
	mi := &file_idl_driver_proto_msgTypes[32]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLicenseReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLicenseReq) ProtoMessage() {}

func (x *UpdateLicenseReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[32]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLicenseReq.ProtoReflect.Descriptor instead.
func (*UpdateLicenseReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{32}
}

func (x *UpdateLicenseReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *UpdateLicenseReq) GetLicenseNo() string {
	if x != nil {
		return x.LicenseNo
	}
	return ""
}

func (x *UpdateLicenseReq) GetLicenseType() string {
	if x != nil {
		return x.LicenseType
	}
	return ""
}

func (x *UpdateLicenseReq) GetLicenseUrl() string {
	if x != nil {
		return x.LicenseUrl
	}
	return ""
}

func (x *UpdateLicenseReq) GetFirstIssueDate() string {
	if x != nil {
		return x.FirstIssueDate
	}
	return ""
}

func (x *UpdateLicenseReq) GetIssueDate() string {
	if x != nil {
		return x.IssueDate
	}
	return ""
}

func (x *UpdateLicenseReq) GetExpireDate() string {
	if x != nil {
		return x.ExpireDate
	}
	return ""
}

type UpdateLicenseResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateLicenseResp) Reset() {
	*x = UpdateLicenseResp{}
	mi := &file_idl_driver_proto_msgTypes[33]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateLicenseResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateLicenseResp) ProtoMessage() {}

func (x *UpdateLicenseResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[33]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateLicenseResp.ProtoReflect.Descriptor instead.
func (*UpdateLicenseResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{33}
}

func (x *UpdateLicenseResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateLicenseResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

// UpdateVehicle 更新/提交车辆信息
type UpdateVehicleReq struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	DriverId          int64                  `protobuf:"varint,1,opt,name=driver_id,json=driverId,proto3" json:"driver_id,omitempty"`
	PlateNo           string                 `protobuf:"bytes,2,opt,name=plate_no,json=plateNo,proto3" json:"plate_no,omitempty"`
	VehicleModel      string                 `protobuf:"bytes,3,opt,name=vehicle_model,json=vehicleModel,proto3" json:"vehicle_model,omitempty"`
	VehicleBrand      string                 `protobuf:"bytes,4,opt,name=vehicle_brand,json=vehicleBrand,proto3" json:"vehicle_brand,omitempty"`
	VehicleColor      string                 `protobuf:"bytes,5,opt,name=vehicle_color,json=vehicleColor,proto3" json:"vehicle_color,omitempty"`
	VehicleColorCode  string                 `protobuf:"bytes,6,opt,name=vehicle_color_code,json=vehicleColorCode,proto3" json:"vehicle_color_code,omitempty"`
	SeatCount         int32                  `protobuf:"varint,7,opt,name=seat_count,json=seatCount,proto3" json:"seat_count,omitempty"`
	DrivingLicenseUrl string                 `protobuf:"bytes,8,opt,name=driving_license_url,json=drivingLicenseUrl,proto3" json:"driving_license_url,omitempty"`
	VehiclePhotoUrl   string                 `protobuf:"bytes,9,opt,name=vehicle_photo_url,json=vehiclePhotoUrl,proto3" json:"vehicle_photo_url,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *UpdateVehicleReq) Reset() {
	*x = UpdateVehicleReq{}
	mi := &file_idl_driver_proto_msgTypes[34]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleReq) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleReq) ProtoMessage() {}

func (x *UpdateVehicleReq) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[34]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleReq.ProtoReflect.Descriptor instead.
func (*UpdateVehicleReq) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{34}
}

func (x *UpdateVehicleReq) GetDriverId() int64 {
	if x != nil {
		return x.DriverId
	}
	return 0
}

func (x *UpdateVehicleReq) GetPlateNo() string {
	if x != nil {
		return x.PlateNo
	}
	return ""
}

func (x *UpdateVehicleReq) GetVehicleModel() string {
	if x != nil {
		return x.VehicleModel
	}
	return ""
}

func (x *UpdateVehicleReq) GetVehicleBrand() string {
	if x != nil {
		return x.VehicleBrand
	}
	return ""
}

func (x *UpdateVehicleReq) GetVehicleColor() string {
	if x != nil {
		return x.VehicleColor
	}
	return ""
}

func (x *UpdateVehicleReq) GetVehicleColorCode() string {
	if x != nil {
		return x.VehicleColorCode
	}
	return ""
}

func (x *UpdateVehicleReq) GetSeatCount() int32 {
	if x != nil {
		return x.SeatCount
	}
	return 0
}

func (x *UpdateVehicleReq) GetDrivingLicenseUrl() string {
	if x != nil {
		return x.DrivingLicenseUrl
	}
	return ""
}

func (x *UpdateVehicleReq) GetVehiclePhotoUrl() string {
	if x != nil {
		return x.VehiclePhotoUrl
	}
	return ""
}

type UpdateVehicleResp struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	Message       string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *UpdateVehicleResp) Reset() {
	*x = UpdateVehicleResp{}
	mi := &file_idl_driver_proto_msgTypes[35]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateVehicleResp) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateVehicleResp) ProtoMessage() {}

func (x *UpdateVehicleResp) ProtoReflect() protoreflect.Message {
	mi := &file_idl_driver_proto_msgTypes[35]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateVehicleResp.ProtoReflect.Descriptor instead.
func (*UpdateVehicleResp) Descriptor() ([]byte, []int) {
	return file_idl_driver_proto_rawDescGZIP(), []int{35}
}

func (x *UpdateVehicleResp) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *UpdateVehicleResp) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

var File_idl_driver_proto protoreflect.FileDescriptor

const file_idl_driver_proto_rawDesc = "" +
	"\n" +
	"\x10idl/driver.proto\x12\x06driver\"%\n" +
	"\x0fCreateDriverReq\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\"\"\n" +
	"\x10CreateDriverResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"\x1e\n" +
	"\fGetDriverReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\"K\n" +
	"\rGetDriverResp\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\"\x0f\n" +
	"\rListDriverReq\"H\n" +
	"\n" +
	"DriverItem\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06status\x18\x03 \x01(\x05R\x06status\":\n" +
	"\x0eListDriverResp\x12(\n" +
	"\x05items\x18\x01 \x03(\v2\x12.driver.DriverItemR\x05items\"5\n" +
	"\x0fUpdateDriverReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\",\n" +
	"\x10UpdateDriverResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"!\n" +
	"\x0fDeleteDriverReq\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\x03R\x02id\",\n" +
	"\x10DeleteDriverResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Z\n" +
	"\x13GetDriverProfileReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x12\n" +
	"\x04date\x18\x02 \x01(\tR\x04date\x12\x12\n" +
	"\x04days\x18\x03 \x01(\x05R\x04days\"\xd6\x02\n" +
	"\x14GetDriverProfileResp\x129\n" +
	"\rpersonal_info\x18\x01 \x01(\v2\x14.driver.PersonalInfoR\fpersonalInfo\x123\n" +
	"\vorder_stats\x18\x02 \x01(\v2\x12.driver.OrderStatsR\n" +
	"orderStats\x12#\n" +
	"\rverify_status\x18\x03 \x01(\x05R\fverifyStatus\x129\n" +
	"\rrealname_info\x18\x04 \x01(\v2\x14.driver.RealnameInfoR\frealnameInfo\x126\n" +
	"\flicense_info\x18\x05 \x01(\v2\x13.driver.LicenseInfoR\vlicenseInfo\x126\n" +
	"\fvehicle_info\x18\x06 \x01(\v2\x13.driver.VehicleInfoR\vvehicleInfo\"\x97\x01\n" +
	"\fRealnameInfo\x12\x1b\n" +
	"\treal_name\x18\x01 \x01(\tR\brealName\x12)\n" +
	"\x11id_card_front_url\x18\x02 \x01(\tR\x0eidCardFrontUrl\x12'\n" +
	"\x10id_card_back_url\x18\x03 \x01(\tR\ridCardBackUrl\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\x88\x01\n" +
	"\vLicenseInfo\x12\x1d\n" +
	"\n" +
	"license_no\x18\x01 \x01(\tR\tlicenseNo\x12!\n" +
	"\flicense_type\x18\x02 \x01(\tR\vlicenseType\x12\x1f\n" +
	"\vlicense_url\x18\x03 \x01(\tR\n" +
	"licenseUrl\x12\x16\n" +
	"\x06status\x18\x04 \x01(\x05R\x06status\"\xaa\x02\n" +
	"\vVehicleInfo\x12\x19\n" +
	"\bplate_no\x18\x01 \x01(\tR\aplateNo\x12#\n" +
	"\rvehicle_brand\x18\x02 \x01(\tR\fvehicleBrand\x12#\n" +
	"\rvehicle_model\x18\x03 \x01(\tR\fvehicleModel\x12#\n" +
	"\rvehicle_color\x18\x04 \x01(\tR\fvehicleColor\x12\x1d\n" +
	"\n" +
	"seat_count\x18\x05 \x01(\x05R\tseatCount\x12.\n" +
	"\x13driving_license_url\x18\x06 \x01(\tR\x11drivingLicenseUrl\x12*\n" +
	"\x11vehicle_photo_url\x18\a \x01(\tR\x0fvehiclePhotoUrl\x12\x16\n" +
	"\x06status\x18\b \x01(\x05R\x06status\"\xf6\x01\n" +
	"\fPersonalInfo\x12\x1a\n" +
	"\bnickname\x18\x01 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x02 \x01(\tR\x06avatar\x12#\n" +
	"\rservice_score\x18\x03 \x01(\x01R\fserviceScore\x12\x1f\n" +
	"\vorder_count\x18\x04 \x01(\x05R\n" +
	"orderCount\x12\x14\n" +
	"\x05phone\x18\x05 \x01(\tR\x05phone\x12\x14\n" +
	"\x05plate\x18\x06 \x01(\tR\x05plate\x12\x10\n" +
	"\x03car\x18\a \x01(\tR\x03car\x12\x16\n" +
	"\x06online\x18\b \x01(\bR\x06online\x12\x16\n" +
	"\x06status\x18\t \x01(\tR\x06status\"n\n" +
	"\n" +
	"OrderStats\x12\x1f\n" +
	"\vorder_count\x18\x01 \x01(\x05R\n" +
	"orderCount\x12\x16\n" +
	"\x06income\x18\x02 \x01(\x01R\x06income\x12'\n" +
	"\x0fonline_duration\x18\x03 \x01(\x05R\x0eonlineDuration\"I\n" +
	"\x12GetDriverIncomeReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x16\n" +
	"\x06period\x18\x02 \x01(\tR\x06period\"9\n" +
	"\vDailyIncome\x12\x12\n" +
	"\x04date\x18\x01 \x01(\tR\x04date\x12\x16\n" +
	"\x06income\x18\x02 \x01(\x01R\x06income\"q\n" +
	"\rIncomeSummary\x12\x1f\n" +
	"\vorder_count\x18\x01 \x01(\x05R\n" +
	"orderCount\x12\x16\n" +
	"\x06income\x18\x02 \x01(\x01R\x06income\x12'\n" +
	"\x0fonline_duration\x18\x03 \x01(\x05R\x0eonlineDuration\"q\n" +
	"\x13GetDriverIncomeResp\x12/\n" +
	"\asummary\x18\x01 \x01(\v2\x15.driver.IncomeSummaryR\asummary\x12)\n" +
	"\x05trend\x18\x02 \x03(\v2\x13.driver.DailyIncomeR\x05trend\"n\n" +
	"\x0fChangeMobileReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x1d\n" +
	"\n" +
	"new_mobile\x18\x02 \x01(\tR\tnewMobile\x12\x1f\n" +
	"\vverify_code\x18\x03 \x01(\tR\n" +
	"verifyCode\"F\n" +
	"\x10ChangeMobileResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"v\n" +
	"\x11ChangePasswordReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12!\n" +
	"\fold_password\x18\x02 \x01(\tR\voldPassword\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"H\n" +
	"\x12ChangePasswordResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"n\n" +
	"\x10ResetPasswordReq\x12\x16\n" +
	"\x06mobile\x18\x01 \x01(\tR\x06mobile\x12\x1f\n" +
	"\vverify_code\x18\x02 \x01(\tR\n" +
	"verifyCode\x12!\n" +
	"\fnew_password\x18\x03 \x01(\tR\vnewPassword\"G\n" +
	"\x11ResetPasswordResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"{\n" +
	"\x10UpdateProfileReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x1a\n" +
	"\bnickname\x18\x02 \x01(\tR\bnickname\x12\x16\n" +
	"\x06avatar\x18\x03 \x01(\tR\x06avatar\x12\x16\n" +
	"\x06gender\x18\x04 \x01(\x05R\x06gender\"G\n" +
	"\x11UpdateProfileResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xc6\x02\n" +
	"\x11UpdateRealnameReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x1b\n" +
	"\treal_name\x18\x02 \x01(\tR\brealName\x12\x1c\n" +
	"\n" +
	"id_card_no\x18\x03 \x01(\tR\bidCardNo\x12)\n" +
	"\x11id_card_front_url\x18\x04 \x01(\tR\x0eidCardFrontUrl\x12'\n" +
	"\x10id_card_back_url\x18\x05 \x01(\tR\ridCardBackUrl\x12\x16\n" +
	"\x06gender\x18\x06 \x01(\x05R\x06gender\x12\x1a\n" +
	"\bbirthday\x18\a \x01(\tR\bbirthday\x12\x18\n" +
	"\aaddress\x18\b \x01(\tR\aaddress\x12\x16\n" +
	"\x06nation\x18\t \x01(\tR\x06nation\x12\x1f\n" +
	"\vexpire_date\x18\n" +
	" \x01(\tR\n" +
	"expireDate\"H\n" +
	"\x12UpdateRealnameResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xfc\x01\n" +
	"\x10UpdateLicenseReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x1d\n" +
	"\n" +
	"license_no\x18\x02 \x01(\tR\tlicenseNo\x12!\n" +
	"\flicense_type\x18\x03 \x01(\tR\vlicenseType\x12\x1f\n" +
	"\vlicense_url\x18\x04 \x01(\tR\n" +
	"licenseUrl\x12(\n" +
	"\x10first_issue_date\x18\x05 \x01(\tR\x0efirstIssueDate\x12\x1d\n" +
	"\n" +
	"issue_date\x18\x06 \x01(\tR\tissueDate\x12\x1f\n" +
	"\vexpire_date\x18\a \x01(\tR\n" +
	"expireDate\"G\n" +
	"\x11UpdateLicenseResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\"\xe2\x02\n" +
	"\x10UpdateVehicleReq\x12\x1b\n" +
	"\tdriver_id\x18\x01 \x01(\x03R\bdriverId\x12\x19\n" +
	"\bplate_no\x18\x02 \x01(\tR\aplateNo\x12#\n" +
	"\rvehicle_model\x18\x03 \x01(\tR\fvehicleModel\x12#\n" +
	"\rvehicle_brand\x18\x04 \x01(\tR\fvehicleBrand\x12#\n" +
	"\rvehicle_color\x18\x05 \x01(\tR\fvehicleColor\x12,\n" +
	"\x12vehicle_color_code\x18\x06 \x01(\tR\x10vehicleColorCode\x12\x1d\n" +
	"\n" +
	"seat_count\x18\a \x01(\x05R\tseatCount\x12.\n" +
	"\x13driving_license_url\x18\b \x01(\tR\x11drivingLicenseUrl\x12*\n" +
	"\x11vehicle_photo_url\x18\t \x01(\tR\x0fvehiclePhotoUrl\"G\n" +
	"\x11UpdateVehicleResp\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage2\xad\a\n" +
	"\rDriverService\x12;\n" +
	"\x06Create\x12\x17.driver.CreateDriverReq\x1a\x18.driver.CreateDriverResp\x122\n" +
	"\x03Get\x12\x14.driver.GetDriverReq\x1a\x15.driver.GetDriverResp\x125\n" +
	"\x04List\x12\x15.driver.ListDriverReq\x1a\x16.driver.ListDriverResp\x12;\n" +
	"\x06Update\x12\x17.driver.UpdateDriverReq\x1a\x18.driver.UpdateDriverResp\x12;\n" +
	"\x06Delete\x12\x17.driver.DeleteDriverReq\x1a\x18.driver.DeleteDriverResp\x12G\n" +
	"\n" +
	"GetProfile\x12\x1b.driver.GetDriverProfileReq\x1a\x1c.driver.GetDriverProfileResp\x12D\n" +
	"\tGetIncome\x12\x1a.driver.GetDriverIncomeReq\x1a\x1b.driver.GetDriverIncomeResp\x12A\n" +
	"\fChangeMobile\x12\x17.driver.ChangeMobileReq\x1a\x18.driver.ChangeMobileResp\x12G\n" +
	"\x0eChangePassword\x12\x19.driver.ChangePasswordReq\x1a\x1a.driver.ChangePasswordResp\x12D\n" +
	"\rResetPassword\x12\x18.driver.ResetPasswordReq\x1a\x19.driver.ResetPasswordResp\x12D\n" +
	"\rUpdateProfile\x12\x18.driver.UpdateProfileReq\x1a\x19.driver.UpdateProfileResp\x12G\n" +
	"\x0eUpdateRealname\x12\x19.driver.UpdateRealnameReq\x1a\x1a.driver.UpdateRealnameResp\x12D\n" +
	"\rUpdateLicense\x12\x18.driver.UpdateLicenseReq\x1a\x19.driver.UpdateLicenseResp\x12D\n" +
	"\rUpdateVehicle\x12\x18.driver.UpdateVehicleReq\x1a\x19.driver.UpdateVehicleRespB!Z\x1ftaketaxi/common/kitexGen/driverb\x06proto3"

var (
	file_idl_driver_proto_rawDescOnce sync.Once
	file_idl_driver_proto_rawDescData []byte
)

func file_idl_driver_proto_rawDescGZIP() []byte {
	file_idl_driver_proto_rawDescOnce.Do(func() {
		file_idl_driver_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_idl_driver_proto_rawDesc), len(file_idl_driver_proto_rawDesc)))
	})
	return file_idl_driver_proto_rawDescData
}

var file_idl_driver_proto_msgTypes = make([]protoimpl.MessageInfo, 36)
var file_idl_driver_proto_goTypes = []any{
	(*CreateDriverReq)(nil),      // 0: driver.CreateDriverReq
	(*CreateDriverResp)(nil),     // 1: driver.CreateDriverResp
	(*GetDriverReq)(nil),         // 2: driver.GetDriverReq
	(*GetDriverResp)(nil),        // 3: driver.GetDriverResp
	(*ListDriverReq)(nil),        // 4: driver.ListDriverReq
	(*DriverItem)(nil),           // 5: driver.DriverItem
	(*ListDriverResp)(nil),       // 6: driver.ListDriverResp
	(*UpdateDriverReq)(nil),      // 7: driver.UpdateDriverReq
	(*UpdateDriverResp)(nil),     // 8: driver.UpdateDriverResp
	(*DeleteDriverReq)(nil),      // 9: driver.DeleteDriverReq
	(*DeleteDriverResp)(nil),     // 10: driver.DeleteDriverResp
	(*GetDriverProfileReq)(nil),  // 11: driver.GetDriverProfileReq
	(*GetDriverProfileResp)(nil), // 12: driver.GetDriverProfileResp
	(*RealnameInfo)(nil),         // 13: driver.RealnameInfo
	(*LicenseInfo)(nil),          // 14: driver.LicenseInfo
	(*VehicleInfo)(nil),          // 15: driver.VehicleInfo
	(*PersonalInfo)(nil),         // 16: driver.PersonalInfo
	(*OrderStats)(nil),           // 17: driver.OrderStats
	(*GetDriverIncomeReq)(nil),   // 18: driver.GetDriverIncomeReq
	(*DailyIncome)(nil),          // 19: driver.DailyIncome
	(*IncomeSummary)(nil),        // 20: driver.IncomeSummary
	(*GetDriverIncomeResp)(nil),  // 21: driver.GetDriverIncomeResp
	(*ChangeMobileReq)(nil),      // 22: driver.ChangeMobileReq
	(*ChangeMobileResp)(nil),     // 23: driver.ChangeMobileResp
	(*ChangePasswordReq)(nil),    // 24: driver.ChangePasswordReq
	(*ChangePasswordResp)(nil),   // 25: driver.ChangePasswordResp
	(*ResetPasswordReq)(nil),     // 26: driver.ResetPasswordReq
	(*ResetPasswordResp)(nil),    // 27: driver.ResetPasswordResp
	(*UpdateProfileReq)(nil),     // 28: driver.UpdateProfileReq
	(*UpdateProfileResp)(nil),    // 29: driver.UpdateProfileResp
	(*UpdateRealnameReq)(nil),    // 30: driver.UpdateRealnameReq
	(*UpdateRealnameResp)(nil),   // 31: driver.UpdateRealnameResp
	(*UpdateLicenseReq)(nil),     // 32: driver.UpdateLicenseReq
	(*UpdateLicenseResp)(nil),    // 33: driver.UpdateLicenseResp
	(*UpdateVehicleReq)(nil),     // 34: driver.UpdateVehicleReq
	(*UpdateVehicleResp)(nil),    // 35: driver.UpdateVehicleResp
}
var file_idl_driver_proto_depIdxs = []int32{
	5,  // 0: driver.ListDriverResp.items:type_name -> driver.DriverItem
	16, // 1: driver.GetDriverProfileResp.personal_info:type_name -> driver.PersonalInfo
	17, // 2: driver.GetDriverProfileResp.order_stats:type_name -> driver.OrderStats
	13, // 3: driver.GetDriverProfileResp.realname_info:type_name -> driver.RealnameInfo
	14, // 4: driver.GetDriverProfileResp.license_info:type_name -> driver.LicenseInfo
	15, // 5: driver.GetDriverProfileResp.vehicle_info:type_name -> driver.VehicleInfo
	20, // 6: driver.GetDriverIncomeResp.summary:type_name -> driver.IncomeSummary
	19, // 7: driver.GetDriverIncomeResp.trend:type_name -> driver.DailyIncome
	0,  // 8: driver.DriverService.Create:input_type -> driver.CreateDriverReq
	2,  // 9: driver.DriverService.Get:input_type -> driver.GetDriverReq
	4,  // 10: driver.DriverService.List:input_type -> driver.ListDriverReq
	7,  // 11: driver.DriverService.Update:input_type -> driver.UpdateDriverReq
	9,  // 12: driver.DriverService.Delete:input_type -> driver.DeleteDriverReq
	11, // 13: driver.DriverService.GetProfile:input_type -> driver.GetDriverProfileReq
	18, // 14: driver.DriverService.GetIncome:input_type -> driver.GetDriverIncomeReq
	22, // 15: driver.DriverService.ChangeMobile:input_type -> driver.ChangeMobileReq
	24, // 16: driver.DriverService.ChangePassword:input_type -> driver.ChangePasswordReq
	26, // 17: driver.DriverService.ResetPassword:input_type -> driver.ResetPasswordReq
	28, // 18: driver.DriverService.UpdateProfile:input_type -> driver.UpdateProfileReq
	30, // 19: driver.DriverService.UpdateRealname:input_type -> driver.UpdateRealnameReq
	32, // 20: driver.DriverService.UpdateLicense:input_type -> driver.UpdateLicenseReq
	34, // 21: driver.DriverService.UpdateVehicle:input_type -> driver.UpdateVehicleReq
	1,  // 22: driver.DriverService.Create:output_type -> driver.CreateDriverResp
	3,  // 23: driver.DriverService.Get:output_type -> driver.GetDriverResp
	6,  // 24: driver.DriverService.List:output_type -> driver.ListDriverResp
	8,  // 25: driver.DriverService.Update:output_type -> driver.UpdateDriverResp
	10, // 26: driver.DriverService.Delete:output_type -> driver.DeleteDriverResp
	12, // 27: driver.DriverService.GetProfile:output_type -> driver.GetDriverProfileResp
	21, // 28: driver.DriverService.GetIncome:output_type -> driver.GetDriverIncomeResp
	23, // 29: driver.DriverService.ChangeMobile:output_type -> driver.ChangeMobileResp
	25, // 30: driver.DriverService.ChangePassword:output_type -> driver.ChangePasswordResp
	27, // 31: driver.DriverService.ResetPassword:output_type -> driver.ResetPasswordResp
	29, // 32: driver.DriverService.UpdateProfile:output_type -> driver.UpdateProfileResp
	31, // 33: driver.DriverService.UpdateRealname:output_type -> driver.UpdateRealnameResp
	33, // 34: driver.DriverService.UpdateLicense:output_type -> driver.UpdateLicenseResp
	35, // 35: driver.DriverService.UpdateVehicle:output_type -> driver.UpdateVehicleResp
	22, // [22:36] is the sub-list for method output_type
	8,  // [8:22] is the sub-list for method input_type
	8,  // [8:8] is the sub-list for extension type_name
	8,  // [8:8] is the sub-list for extension extendee
	0,  // [0:8] is the sub-list for field type_name
}

func init() { file_idl_driver_proto_init() }
func file_idl_driver_proto_init() {
	if File_idl_driver_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_idl_driver_proto_rawDesc), len(file_idl_driver_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   36,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_idl_driver_proto_goTypes,
		DependencyIndexes: file_idl_driver_proto_depIdxs,
		MessageInfos:      file_idl_driver_proto_msgTypes,
	}.Build()
	File_idl_driver_proto = out.File
	file_idl_driver_proto_goTypes = nil
	file_idl_driver_proto_depIdxs = nil
}
